/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './modal.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '@angular/common/src/directives/ng_class';
import * as import11 from '@angular/common/src/directives/ng_style';
import * as import12 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import13 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import14 from '@angular/core/src/linker/element_ref';
var renderType_ModalComponent_Host:import0.RenderComponentType = (null as any);
class _View_ModalComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ModalComponent_0_4:import3.ModalComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalComponent_Host0,renderType_ModalComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-modal',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ModalComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ModalComponent_0_4 = new import3.ModalComponent();
    this._appEl_0.initComponent(this._ModalComponent_0_4,[],compView_0);
    compView_0.create(this._ModalComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ModalComponent) && (0 === requestNodeIndex))) { return this._ModalComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ModalComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ModalComponent_Host === (null as any))) { (renderType_ModalComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_ModalComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ModalComponentNgFactory:import9.ComponentFactory<import3.ModalComponent> = new import9.ComponentFactory<import3.ModalComponent>('app-modal',viewFactory_ModalComponent_Host0,import3.ModalComponent);
const styles_ModalComponent:any[] = [];
var renderType_ModalComponent:import0.RenderComponentType = (null as any);
class _View_ModalComponent0 extends import1.AppView<import3.ModalComponent> {
  _el_0:any;
  _NgClass_0_3:import10.NgClass;
  _NgStyle_0_4:import11.NgStyle;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_0:any;
  _map_0:any;
  /*private*/ _expr_1:any;
  _map_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ModalComponent0,renderType_ModalComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','modal fade');
    this.renderer.setElementAttribute(this._el_0,'tabindex','-1');
    this._NgClass_0_3 = new import10.NgClass(this.parentInjector.get(import12.IterableDiffers),this.parentInjector.get(import13.KeyValueDiffers),new import14.ElementRef(this._el_0),this.renderer);
    this._NgStyle_0_4 = new import11.NgStyle(this.parentInjector.get(import13.KeyValueDiffers),new import14.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','modal-dialog');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','modal-content');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','modal-header');
    this._text_7 = this.renderer.createText(this._el_6,'\n                ',(null as any));
    this.renderer.projectNodes(this._el_6,import4.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_8 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._text_9 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','modal-body');
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this.renderer.projectNodes(this._el_10,import4.flattenNestedViewRenderNodes(this.projectableNodes[1]));
    this._text_12 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','modal-footer');
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this.renderer.projectNodes(this._el_14,import4.flattenNestedViewRenderNodes(this.projectableNodes[2]));
    this._text_16 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_17 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_18 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy1((p0:any):{[key: string]:any} => {
      return {in: p0};
    });
    this._expr_1 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        display: p0,
        opacity: p1
      }
      ;
    });
    this._expr_2 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import10.NgClass) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgClass_0_3; }
    if (((token === import11.NgStyle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgStyle_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'modal fade';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgClass_0_3.klass = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._map_0(this.context.visibleAnimate);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_0_3.ngClass = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (!throwOnChange) { this._NgClass_0_3.ngDoCheck(); }
    const currVal_2:any = this._map_1((this.context.visible? 'block': 'none'),(this.context.visibleAnimate? 1: 0));
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgStyle_0_4.ngStyle = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgStyle_0_4.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ModalComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ModalComponent> {
  if ((renderType_ModalComponent === (null as any))) { (renderType_ModalComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/theme_details/modal.component.html',3,import8.ViewEncapsulation.None,styles_ModalComponent,{})); }
  return new _View_ModalComponent0(viewUtils,parentInjector,declarationEl);
}