/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './theme-details.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../services/theme.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '../error-handling/error.component';
import * as import16 from './modal.component';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from '../error-handling/error.component.ngfactory';
import * as import19 from '../error-handling/error.service';
import * as import20 from './modal.component.ngfactory';
import * as import21 from './theme-properties.component';
import * as import22 from '../stock_allocation/theme-stock-allocation.component';
import * as import23 from './theme-properties.component.ngfactory';
import * as import24 from '../stock_allocation/theme-stock-allocation.component.ngfactory';
import * as import25 from '../theme_creation/theme-characteristics-editing.component';
import * as import26 from '../theme_creation/theme-characteristics-editing.component.ngfactory';
var renderType_ThemeDetailsComponent_Host:import0.RenderComponentType = (null as any);
class _View_ThemeDetailsComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ThemeDetailsComponent_0_4:import3.ThemeDetailsComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeDetailsComponent_Host0,renderType_ThemeDetailsComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-theme-details',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ThemeDetailsComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ThemeDetailsComponent_0_4 = new import3.ThemeDetailsComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.ThemeService));
    this._appEl_0.initComponent(this._ThemeDetailsComponent_0_4,[],compView_0);
    compView_0.create(this._ThemeDetailsComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ThemeDetailsComponent) && (0 === requestNodeIndex))) { return this._ThemeDetailsComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ThemeDetailsComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemeDetailsComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ThemeDetailsComponent_Host === (null as any))) { (renderType_ThemeDetailsComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_ThemeDetailsComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ThemeDetailsComponentNgFactory:import12.ComponentFactory<import3.ThemeDetailsComponent> = new import12.ComponentFactory<import3.ThemeDetailsComponent>('app-theme-details',viewFactory_ThemeDetailsComponent_Host0,import3.ThemeDetailsComponent);
const styles_ThemeDetailsComponent:any[] = ['h3[_ngcontent-%COMP%] {\n                margin-top: 0;\n            }\n            .well[_ngcontent-%COMP%]   button.btn-default[_ngcontent-%COMP%] {\n                background-color: #f5f5f5;\n                text-decoration: none;\n                outline:none;\n                border: none;\n                box-shadow: none;\n            }, .modal[_ngcontent-%COMP%] {\n              background: rgba(0,0,0,0.6);\n            }'];
var renderType_ThemeDetailsComponent:import0.RenderComponentType = (null as any);
class _View_ThemeDetailsComponent0 extends import1.AppView<import3.ThemeDetailsComponent> {
  _viewQuery_ModalComponent_0:import13.QueryList<any>;
  _anchor_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TemplateRef_0_5:any;
  _NgIf_0_6:import14.NgIf;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _ErrorComponent_2_4:import15.ErrorComponent;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _ModalComponent_5_4:import16.ModalComponent;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeDetailsComponent0,renderType_ThemeDetailsComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_ModalComponent_0 = new import13.QueryList<any>();
    this._anchor_0 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._anchor_0);
    this._TemplateRef_0_5 = new import17.TemplateRef_(this._appEl_0,viewFactory_ThemeDetailsComponent1);
    this._NgIf_0_6 = new import14.NgIf(this._appEl_0.vcRef,this._TemplateRef_0_5);
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_2 = this.renderer.createElement(parentRenderNode,'app-error',(null as any));
    this._appEl_2 = new import2.AppElement(2,(null as any),this,this._el_2);
    var compView_2:any = import18.viewFactory_ErrorComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._ErrorComponent_2_4 = new import15.ErrorComponent(this.parentInjector.get(import19.ErrorService));
    this._appEl_2.initComponent(this._ErrorComponent_2_4,[],compView_2);
    compView_2.create(this._ErrorComponent_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_5 = this.renderer.createElement(parentRenderNode,'app-modal',(null as any));
    this._appEl_5 = new import2.AppElement(5,(null as any),this,this._el_5);
    var compView_5:any = import20.viewFactory_ModalComponent0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ModalComponent_5_4 = new import16.ModalComponent();
    this._appEl_5.initComponent(this._ModalComponent_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','app-modal-header');
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'h5',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Delete Theme',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','app-modal-body');
    this._text_14 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'p',(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'Are you sure you want to delete this theme and all its properties and stock allocation data?',(null as any));
    this._text_17 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','app-modal-footer');
    this._text_20 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_21,'type','button');
    this._text_22 = this.renderer.createText(this._el_21,'Close',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_19,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_24,'type','button');
    this._text_25 = this.renderer.createText(this._el_24,'Delete',(null as any));
    this._text_26 = this.renderer.createText(this._el_19,'\n    ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n',(null as any));
    compView_5.create(this._ModalComponent_5_4,[
      [].concat([this._el_7]),
      [].concat([this._el_13]),
      [].concat([this._el_19])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this._viewQuery_ModalComponent_0.reset([this._ModalComponent_5_4]);
    this.context.modal = this._viewQuery_ModalComponent_0.first;
    this.init([],[
      this._anchor_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (0 === requestNodeIndex))) { return this._TemplateRef_0_5; }
    if (((token === import14.NgIf) && (0 === requestNodeIndex))) { return this._NgIf_0_6; }
    if (((token === import15.ErrorComponent) && (2 === requestNodeIndex))) { return this._ErrorComponent_2_4; }
    if (((token === import16.ModalComponent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ModalComponent_5_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.theme;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_0_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ErrorComponent_2_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._ModalComponent_5_4.hide()) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.deleteTheme(this._ModalComponent_5_4)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ThemeDetailsComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ThemeDetailsComponent> {
  if ((renderType_ThemeDetailsComponent === (null as any))) { (renderType_ThemeDetailsComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/theme_details/theme-details.component.html',0,import11.ViewEncapsulation.Emulated,styles_ThemeDetailsComponent,{})); }
  return new _View_ThemeDetailsComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeDetailsComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import14.NgIf;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _TemplateRef_28_5:any;
  _NgIf_28_6:import14.NgIf;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import2.AppElement;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import14.NgIf;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _ThemePropertiesComponent_34_4:import21.ThemePropertiesComponent;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _ThemeStockAllocationComponent_37_4:import22.ThemeStockAllocationComponent;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeDetailsComponent1,renderType_ThemeDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','well');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-xs-10 text-center');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h3',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'p',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_12 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','col-xs-2 text-right');
    this._text_14 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','btn-group-vertical');
    this.renderer.setElementAttribute(this._el_15,'role','group');
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_17 = new import2.AppElement(17,15,this,this._anchor_17);
    this._TemplateRef_17_5 = new import17.TemplateRef_(this._appEl_17,viewFactory_ThemeDetailsComponent2);
    this._NgIf_17_6 = new import14.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_15,'\n\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_15,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','btn btn-success');
    this._text_20 = this.renderer.createText(this._el_19,'Confirm',(null as any));
    this._text_21 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n            ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_13,'p',(null as any));
    this._el_24 = this.renderer.createElement(this._el_23,'i',(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'[coming soon]',(null as any));
    this._text_26 = this.renderer.createText(this._el_13,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_28 = new import2.AppElement(28,2,this,this._anchor_28);
    this._TemplateRef_28_5 = new import17.TemplateRef_(this._appEl_28,viewFactory_ThemeDetailsComponent3);
    this._NgIf_28_6 = new import14.NgIf(this._appEl_28.vcRef,this._TemplateRef_28_5);
    this._text_29 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_30 = new import2.AppElement(30,2,this,this._anchor_30);
    this._TemplateRef_30_5 = new import17.TemplateRef_(this._appEl_30,viewFactory_ThemeDetailsComponent4);
    this._NgIf_30_6 = new import14.NgIf(this._appEl_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_0,'app-theme-properties',(null as any));
    this._appEl_34 = new import2.AppElement(34,0,this,this._el_34);
    var compView_34:any = import23.viewFactory_ThemePropertiesComponent0(this.viewUtils,this.injector(34),this._appEl_34);
    this._ThemePropertiesComponent_34_4 = new import21.ThemePropertiesComponent(this.parentInjector.get(import10.ThemeService));
    this._appEl_34.initComponent(this._ThemePropertiesComponent_34_4,[],compView_34);
    compView_34.create(this._ThemePropertiesComponent_34_4,[],(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_0,'app-theme-stock-allocation',(null as any));
    this._appEl_37 = new import2.AppElement(37,0,this,this._el_37);
    var compView_37:any = import24.viewFactory_ThemeStockAllocationComponent0(this.viewUtils,this.injector(37),this._appEl_37);
    this._ThemeStockAllocationComponent_37_4 = new import22.ThemeStockAllocationComponent(this.parentInjector.get(import10.ThemeService));
    this._appEl_37.initComponent(this._ThemeStockAllocationComponent_37_4,[],compView_37);
    compView_37.create(this._ThemeStockAllocationComponent_37_4,[],(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import14.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    if (((token === import17.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import14.NgIf) && (28 === requestNodeIndex))) { return this._NgIf_28_6; }
    if (((token === import17.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import14.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6; }
    if (((token === import21.ThemePropertiesComponent) && (34 === requestNodeIndex))) { return this._ThemePropertiesComponent_34_4; }
    if (((token === import22.ThemeStockAllocationComponent) && (37 === requestNodeIndex))) { return this._ThemeStockAllocationComponent_37_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.parent.context.isCurrentUserCreator;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_17_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:boolean = !this.parent.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_28_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.parent.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_30_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.parent.context.selectedThemeId;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._ThemePropertiesComponent_34_4.themeId = currVal_5;
      this._expr_5 = currVal_5;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ThemePropertiesComponent_34_4.ngOnInit(); }
    const currVal_6:any = this.parent.context.selectedThemeId;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._ThemeStockAllocationComponent_37_4.themeId = currVal_6;
      this._expr_6 = currVal_6;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ThemeStockAllocationComponent_37_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.theme.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(2,'Created on: ',this.parent.context.theme.createdAt,', by ',((this.parent.context.theme.creator == (null as any))? (null as any): this.parent.context.theme.creator.name),'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemeDetailsComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeDetailsComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeDetailsComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeDetailsComponent2,renderType_ThemeDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_2,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default dropdown-toggle borderless');
    this.renderer.setElementAttribute(this._el_2,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_2,'type','button');
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'span',(null as any));
    this.renderer.setElementAttribute(this._el_4,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_4,'class','glyphicon glyphicon-pencil');
    this._text_5 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','dropdown-menu');
    this._text_8 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'li',(null as any));
    this._el_10 = this.renderer.createElement(this._el_9,'a',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Edit',(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_7,'li',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','divider');
    this.renderer.setElementAttribute(this._el_13,'role','separator');
    this._text_14 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_7,'li',(null as any));
    this._el_16 = this.renderer.createElement(this._el_15,'a',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'Delete',(null as any));
    this._text_18 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.toggleEditMode()) !== false);
    return (true && pd_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(<_View_ThemeDetailsComponent0>this.parent.parent)._ModalComponent_5_4.show()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeDetailsComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeDetailsComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeDetailsComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeDetailsComponent3,renderType_ThemeDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-xs-2');
    this._text_5 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'label',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Theme description',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','col-xs-10');
    this._text_11 = this.renderer.createText(this._el_10,'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'p',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._text_15 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','row');
    this._text_18 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','col-xs-2');
    this._text_20 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'label',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'Tags',(null as any));
    this._text_23 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n                ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_17,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','col-xs-10');
    this._text_26 = this.renderer.createText(this._el_25,'\n                    ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'p',(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n                ',(null as any));
    this._text_30 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.parent.context.theme.description,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_13,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.parent.context.theme.tags,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_28,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemeDetailsComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeDetailsComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeDetailsComponent4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ThemeCharacteristicsEditing_0_4:import25.ThemeCharacteristicsEditing;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeDetailsComponent4,renderType_ThemeDetailsComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'app-theme-characteristics-editing',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import26.viewFactory_ThemeCharacteristicsEditing0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ThemeCharacteristicsEditing_0_4 = new import25.ThemeCharacteristicsEditing(this.parent.parentInjector.get(import10.ThemeService));
    this._appEl_0.initComponent(this._ThemeCharacteristicsEditing_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    compView_0.create(this._ThemeCharacteristicsEditing_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'themeEmitter',this.eventHandler(this._handle_themeEmitter_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    const subscription_0:any = this._ThemeCharacteristicsEditing_0_4.themeEmitter.subscribe(this.eventHandler(this._handle_themeEmitter_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.ThemeCharacteristicsEditing) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ThemeCharacteristicsEditing_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.parent.parent.context.theme;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ThemeCharacteristicsEditing_0_4.theme = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['theme'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.parent.context.theme.tags;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._ThemeCharacteristicsEditing_0_4.themeTags = currVal_2;
      if ((changes === (null as any))) { (changes = {}); }
      changes['themeTags'] = new import7.SimpleChange(this._expr_2,currVal_2);
      this._expr_2 = currVal_2;
    }
    if ((changes !== (null as any))) { this._ThemeCharacteristicsEditing_0_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_themeEmitter_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.onThemeChanged($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeDetailsComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeDetailsComponent4(viewUtils,parentInjector,declarationEl);
}