/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './theme-properties.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../services/theme.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from './modal.component';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from './modal.component.ngfactory';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/forms/src/directives/control_container';
import * as import21 from '@angular/core/src/security';
var renderType_ThemePropertiesComponent_Host:import0.RenderComponentType = (null as any);
class _View_ThemePropertiesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ThemePropertiesComponent_0_4:import3.ThemePropertiesComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent_Host0,renderType_ThemePropertiesComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-theme-properties',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ThemePropertiesComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ThemePropertiesComponent_0_4 = new import3.ThemePropertiesComponent(this.parentInjector.get(import8.ThemeService));
    this._appEl_0.initComponent(this._ThemePropertiesComponent_0_4,[],compView_0);
    compView_0.create(this._ThemePropertiesComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ThemePropertiesComponent) && (0 === requestNodeIndex))) { return this._ThemePropertiesComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ThemePropertiesComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemePropertiesComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ThemePropertiesComponent_Host === (null as any))) { (renderType_ThemePropertiesComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ThemePropertiesComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ThemePropertiesComponentNgFactory:import10.ComponentFactory<import3.ThemePropertiesComponent> = new import10.ComponentFactory<import3.ThemePropertiesComponent>('app-theme-properties',viewFactory_ThemePropertiesComponent_Host0,import3.ThemePropertiesComponent);
const styles_ThemePropertiesComponent:any[] = ['button.no-decoration-element[_ngcontent-%COMP%], label.no-decoration-element[_ngcontent-%COMP%]:hover, label.no-decoration-element[_ngcontent-%COMP%]:focus {\n            background-color: white;\n            text-decoration: none;\n            outline:none;\n            border: none;\n            box-shadow: none;\n        }\n        label.inactive-element[_ngcontent-%COMP%]:hover, label.inactive-element[_ngcontent-%COMP%]:not(:hover), label.inactive-element[_ngcontent-%COMP%]:focus {\n            text-decoration: none;\n            outline:none;\n            box-shadow: none;\n            border-color: #ccc;\n            cursor: default;    \n        }\n        .btn.active[_ngcontent-%COMP%] {\n            background-color: #d9edf7;\n        }\n        input[type="radio"][_ngcontent-%COMP%], input[type="checkbox"][_ngcontent-%COMP%] {\n            visibility:hidden;\n        }\n        .modal[_ngcontent-%COMP%] {\n            background: rgba(0,0,0,0.6);\n        }\n        .dropdown-toggle[_ngcontent-%COMP%]:active {\n            background: white;\n        }\n        .open[_ngcontent-%COMP%] > .dropdown-toggle[_ngcontent-%COMP%] {\n            background: white;\n            box-shadow: none;\n        }'];
var renderType_ThemePropertiesComponent:import0.RenderComponentType = (null as any);
class _View_ThemePropertiesComponent0 extends import1.AppView<import3.ThemePropertiesComponent> {
  _viewQuery_ModalComponent_0:import11.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import12.NgIf;
  _text_8:any;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import12.NgIf;
  _text_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import12.NgIf;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _ModalComponent_16_4:import13.ModalComponent;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent0,renderType_ThemePropertiesComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_ModalComponent_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','text-center');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h3',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Theme properties',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_7 = new import2.AppElement(7,2,this,this._anchor_7);
    this._TemplateRef_7_5 = new import14.TemplateRef_(this._appEl_7,viewFactory_ThemePropertiesComponent1);
    this._NgIf_7_6 = new import12.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_10 = new import2.AppElement(10,0,this,this._anchor_10);
    this._TemplateRef_10_5 = new import14.TemplateRef_(this._appEl_10,viewFactory_ThemePropertiesComponent2);
    this._NgIf_10_6 = new import12.NgIf(this._appEl_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_13 = new import2.AppElement(13,(null as any),this,this._anchor_13);
    this._TemplateRef_13_5 = new import14.TemplateRef_(this._appEl_13,viewFactory_ThemePropertiesComponent5);
    this._NgIf_13_6 = new import12.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_15 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_16 = this.renderer.createElement(parentRenderNode,'app-modal',(null as any));
    this._appEl_16 = new import2.AppElement(16,(null as any),this,this._el_16);
    var compView_16:any = import15.viewFactory_ModalComponent0(this.viewUtils,this.injector(16),this._appEl_16);
    this._ModalComponent_16_4 = new import13.ModalComponent();
    this._appEl_16.initComponent(this._ModalComponent_16_4,[],compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','app-modal-header');
    this._text_19 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'h5',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'Delete your input',(null as any));
    this._text_22 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_24 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','app-modal-body');
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'p',(null as any));
    this._text_27 = this.renderer.createText(this._el_26,'Are you sure you want to delete your input to this theme?',(null as any));
    this._text_28 = this.renderer.createText(this._el_24,'\n    ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','app-modal-footer');
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'button',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_32,'type','button');
    this._text_33 = this.renderer.createText(this._el_32,'Close',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_30,'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_35,'type','button');
    this._text_36 = this.renderer.createText(this._el_35,'Delete',(null as any));
    this._text_37 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n',(null as any));
    compView_16.create(this._ModalComponent_16_4,[
      [].concat([this._el_18]),
      [].concat([this._el_24]),
      [].concat([this._el_30])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_32,'click',this.eventHandler(this._handle_click_32_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_35,'click',this.eventHandler(this._handle_click_35_0.bind(this)));
    this._viewQuery_ModalComponent_0.reset([this._ModalComponent_16_4]);
    this.context.modal = this._viewQuery_ModalComponent_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import12.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import14.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import12.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6; }
    if (((token === import14.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import12.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import13.ModalComponent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ModalComponent_16_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.themePropertiesData;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_7_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:boolean = !this.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_10_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.themePropertiesData;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_13_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._ModalComponent_16_4.hide()) !== false);
    return (true && pd_0);
  }
  private _handle_click_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.deleteUserThemeInput(this._ModalComponent_16_4)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ThemePropertiesComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ThemePropertiesComponent> {
  if ((renderType_ThemePropertiesComponent === (null as any))) { (renderType_ThemePropertiesComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/theme_details/theme-properties.component.html',0,import9.ViewEncapsulation.Emulated,styles_ThemePropertiesComponent,{})); }
  return new _View_ThemePropertiesComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent1,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'Total votes: ',this.parent.context.themePropertiesData.totalCount,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemePropertiesComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _anchor_15:any;
  /*private*/ _appEl_15:import2.AppElement;
  _TemplateRef_15_5:any;
  _NgIf_15_6:import12.NgIf;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import2.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import12.NgIf;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent2,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','text-right');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn-group');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'button',(null as any));
    this.renderer.setElementAttribute(this._el_4,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_4,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_4,'class','btn btn-default dropdown-toggle borderless no-decoration-element');
    this.renderer.setElementAttribute(this._el_4,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_4,'type','button');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'span',(null as any));
    this.renderer.setElementAttribute(this._el_6,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_6,'class','glyphicon glyphicon-pencil');
    this._text_7 = this.renderer.createText(this._el_4,'\n                Provide your view\n            ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_2,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','dropdown-menu');
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'li',(null as any));
    this._el_12 = this.renderer.createElement(this._el_11,'a',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'Edit',(null as any));
    this._text_14 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._anchor_15 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_15 = new import2.AppElement(15,9,this,this._anchor_15);
    this._TemplateRef_15_5 = new import14.TemplateRef_(this._appEl_15,viewFactory_ThemePropertiesComponent3);
    this._NgIf_15_6 = new import12.NgIf(this._appEl_15.vcRef,this._TemplateRef_15_5);
    this._text_16 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_17 = new import2.AppElement(17,9,this,this._anchor_17);
    this._TemplateRef_17_5 = new import14.TemplateRef_(this._appEl_17,viewFactory_ThemePropertiesComponent4);
    this._NgIf_17_6 = new import12.NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_19 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_12,'click',this.eventHandler(this._handle_click_12_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._anchor_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19,
      this._text_20
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (15 === requestNodeIndex))) { return this._TemplateRef_15_5; }
    if (((token === import12.NgIf) && (15 === requestNodeIndex))) { return this._NgIf_15_6; }
    if (((token === import14.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import12.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = ((this.parent.context.themePropertiesData == (null as any))? (null as any): this.parent.context.themePropertiesData.userInputs);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_15_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = ((this.parent.context.themePropertiesData == (null as any))? (null as any): this.parent.context.themePropertiesData.userInputs);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_17_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_12_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.clearEditing(this.parent.context.propertiesContainer)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent3,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','divider');
    this.renderer.setElementAttribute(this._el_0,'role','separator');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_ThemePropertiesComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent4 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent4,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'type','button');
    this._text_2 = this.renderer.createText(this._el_1,'Delete',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(<_View_ThemePropertiesComponent0>this.parent.parent)._ModalComponent_16_4.show()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import16.NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import17.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _appEl_11:import2.AppElement;
  _TemplateRef_11_5:any;
  _NgFor_11_6:import18.NgFor;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _anchor_22:any;
  /*private*/ _appEl_22:import2.AppElement;
  _TemplateRef_22_5:any;
  _NgFor_22_6:import18.NgFor;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import2.AppElement;
  _TemplateRef_33_5:any;
  _NgFor_33_6:import18.NgFor;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import12.NgIf;
  _text_38:any;
  _text_39:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent5,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_2_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3;
    this._NgControlStatusGroup_2_5 = new import17.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','form-group row');
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h5',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'Expected Time Horizon',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n\n            ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','btn-group btn-group-justified');
    this._text_10 = this.renderer.createText(this._el_9,'\n                ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._appEl_11 = new import2.AppElement(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import14.TemplateRef_(this._appEl_11,viewFactory_ThemePropertiesComponent6);
    this._NgFor_11_6 = new import18.NgFor(this._appEl_11.vcRef,this._TemplateRef_11_5,this.parentInjector.get(import19.IterableDiffers),this.parent.ref);
    this._text_12 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._text_13 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','form-group row');
    this._text_16 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'h5',(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Current theme maturity',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_15,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','btn-group btn-group-justified');
    this._text_21 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._anchor_22 = this.renderer.createTemplateAnchor(this._el_20,(null as any));
    this._appEl_22 = new import2.AppElement(22,20,this,this._anchor_22);
    this._TemplateRef_22_5 = new import14.TemplateRef_(this._appEl_22,viewFactory_ThemePropertiesComponent7);
    this._NgFor_22_6 = new import18.NgFor(this._appEl_22.vcRef,this._TemplateRef_22_5,this.parentInjector.get(import19.IterableDiffers),this.parent.ref);
    this._text_23 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._text_24 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','form-group row');
    this._text_27 = this.renderer.createText(this._el_26,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'h5',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Theme category',(null as any));
    this._text_30 = this.renderer.createText(this._el_26,'\n\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','btn-group btn-group-justified');
    this._text_32 = this.renderer.createText(this._el_31,'\n                ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_31,(null as any));
    this._appEl_33 = new import2.AppElement(33,31,this,this._anchor_33);
    this._TemplateRef_33_5 = new import14.TemplateRef_(this._appEl_33,viewFactory_ThemePropertiesComponent8);
    this._NgFor_33_6 = new import18.NgFor(this._appEl_33.vcRef,this._TemplateRef_33_5,this.parentInjector.get(import19.IterableDiffers),this.parent.ref);
    this._text_34 = this.renderer.createText(this._el_31,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_2,(null as any));
    this._appEl_37 = new import2.AppElement(37,2,this,this._anchor_37);
    this._TemplateRef_37_5 = new import14.TemplateRef_(this._appEl_37,viewFactory_ThemePropertiesComponent9);
    this._NgIf_37_6 = new import12.NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_39 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngSubmit',this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_2.bind(this)));
    const subscription_0:any = this._NgForm_2_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._anchor_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import18.NgFor) && (11 === requestNodeIndex))) { return this._NgFor_11_6; }
    if (((token === import14.TemplateRef) && (22 === requestNodeIndex))) { return this._TemplateRef_22_5; }
    if (((token === import18.NgFor) && (22 === requestNodeIndex))) { return this._NgFor_22_6; }
    if (((token === import14.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import18.NgFor) && (33 === requestNodeIndex))) { return this._NgFor_33_6; }
    if (((token === import14.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import12.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6; }
    if (((token === import16.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgForm_2_3; }
    if (((token === import20.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatusGroup_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_10:any = ((this.parent.context.themePropertiesData == (null as any))? (null as any): ((this.parent.context.themePropertiesData.properties == (null as any))? (null as any): this.parent.context.themePropertiesData.properties.timeHorizon));
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgFor_11_6.ngForOf = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._NgFor_11_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_11_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_12:any = ((this.parent.context.themePropertiesData == (null as any))? (null as any): ((this.parent.context.themePropertiesData.properties == (null as any))? (null as any): this.parent.context.themePropertiesData.properties.maturity));
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgFor_22_6.ngForOf = currVal_12;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_12,currVal_12);
      this._expr_12 = currVal_12;
    }
    if ((changes !== (null as any))) { this._NgFor_22_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_22_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_14:any = ((this.parent.context.themePropertiesData == (null as any))? (null as any): ((this.parent.context.themePropertiesData.properties == (null as any))? (null as any): this.parent.context.themePropertiesData.properties.categories));
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._NgFor_33_6.ngForOf = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._NgFor_33_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_33_6.ngDoCheck(); }
    const currVal_15:any = this.parent.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgIf_37_6.ngIf = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.parent.context.setDataToggleAttribute();
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementAttribute(this._el_9,'data-toggle',((currVal_9 == (null as any))? (null as any): currVal_9.toString()));
      this._expr_9 = currVal_9;
    }
    const currVal_11:any = this.parent.context.setDataToggleAttribute();
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementAttribute(this._el_20,'data-toggle',((currVal_11 == (null as any))? (null as any): currVal_11.toString()));
      this._expr_11 = currVal_11;
    }
    const currVal_13:any = this.parent.context.setDataToggleAttribute();
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_31,'data-toggle',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_ngSubmit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.createOrUpdateThemeProperty(this._NgForm_2_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onReset()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent6 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent6,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'input',(null as any));
    this.renderer.setElementAttribute(this._el_4,'disabled','disabled');
    this.renderer.setElementAttribute(this._el_4,'id','timeHorizon');
    this.renderer.setElementAttribute(this._el_4,'name','timeHorizon');
    this.renderer.setElementAttribute(this._el_4,'type','radio');
    this._text_5 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'p',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','text-center');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.parent.context.setBackgroundColor(((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.percentage));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_2,'backgroundColor',((this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.parent.context.setBorder('timeHorizon',this.context.index);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_2,'borderBottom',((this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_2).toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_3:boolean = !this.parent.parent.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'inactive-element',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.index;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'value',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.percentage),'%\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.parent.parent.context.timeHorizonValues[this.context.index].description,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_8,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.themeProperties.setTimeHorizon(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent7,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'input',(null as any));
    this.renderer.setElementAttribute(this._el_4,'disabled','disabled');
    this.renderer.setElementAttribute(this._el_4,'id','maturity');
    this.renderer.setElementAttribute(this._el_4,'name','maturity');
    this.renderer.setElementAttribute(this._el_4,'type','radio');
    this._text_5 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'p',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','text-center');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.parent.context.setBackgroundColor(((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.percentage));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_2,'backgroundColor',((this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.parent.context.setBorder('maturity',this.context.index);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_2,'borderBottom',((this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_2).toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_3:boolean = !this.parent.parent.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'inactive-element',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.index;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'value',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.percentage),'%\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.parent.parent.context.maturityValues[this.context.index].description,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_8,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.themeProperties.setMaturity(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent8,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default');
    this._text_3 = this.renderer.createText(this._el_2,'\n                        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'input',(null as any));
    this.renderer.setElementAttribute(this._el_4,'disabled','disabled');
    this.renderer.setElementAttribute(this._el_4,'id','categories');
    this.renderer.setElementAttribute(this._el_4,'name','categories');
    this.renderer.setElementAttribute(this._el_4,'required','');
    this.renderer.setElementAttribute(this._el_4,'type','checkbox');
    this._text_5 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'p',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','text-center');
    this._text_8 = this.renderer.createText(this._el_7,'',(null as any));
    this._text_9 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.parent.parent.context.setBackgroundColor(((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.percentage));
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_2,'backgroundColor',((this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.parent.context.setBorder('categories',this.context.index);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementStyle(this._el_2,'borderBottom',((this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_2) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import21.SecurityContext.STYLE,currVal_2).toString()));
      this._expr_2 = currVal_2;
    }
    const currVal_3:boolean = !this.parent.parent.context.isEditMode;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'inactive-element',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.index;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_4,'value',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'',((this.context.$implicit == (null as any))? (null as any): this.context.$implicit.percentage),'%\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,'',this.parent.parent.context.categoryValues[this.context.index].description,'');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_8,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.themeProperties.toggleCheckedCategory(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_ThemePropertiesComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemePropertiesComponent9,renderType_ThemePropertiesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','text-right');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_2,'type','button');
    this._text_3 = this.renderer.createText(this._el_2,'Cancel',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_5,'type','submit');
    this._text_6 = this.renderer.createText(this._el_5,'Save',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'click',this.eventHandler(this._handle_click_2_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:boolean = (!(<_View_ThemePropertiesComponent5>this.parent)._NgForm_2_3.form.valid || this.parent.parent.context.themeProperties.hasNoUserInputs());
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_5,'disabled',currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.clearEditing((<_View_ThemePropertiesComponent5>this.parent)._el_0)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemePropertiesComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemePropertiesComponent9(viewUtils,parentInjector,declarationEl);
}