module.exports = {
    MIN_TIME_HORIZON: 0,
    MAX_TIME_HORIZON: 2,
    TOTAL_TIME_HORIZON_VALUES: 3,
    MIN_MATURITY: 0,
    MAX_MATURITY: 4,
    TOTAL_MATURITY_VALUES: 5,
    MIN_CATEGORY: 0,
    MAX_CATEGORY: 5,
    TOTAL_CATEGORY_VALUES: 6,
    MIN_EXPOSURE: 0,
    MAX_EXPOSURE: 4,
    TOTAL_EXPOSURE_VALUES: 5
}