/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './theme-stock-allocation.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../services/theme.service';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '@angular/common/src/directives/ng_if';
import * as import13 from '../theme_details/modal.component';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '../theme_details/modal.component.ngfactory';
import * as import16 from '@angular/common/src/directives/ng_for';
import * as import17 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import18 from '@angular/forms/src/directives/ng_form';
import * as import19 from '@angular/forms/src/directives/ng_control_status';
import * as import20 from '@angular/forms/src/directives/control_container';
import * as import21 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import22 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/core/src/security';
import * as import25 from '../autocomplete/autocomplete-datasource.service';
import * as import26 from '../autocomplete/autocomplete-stock-allocation.component';
import * as import27 from '../autocomplete/autocomplete-stock-allocation.component.ngfactory';
import * as import28 from '@angular/http/src/http';
import * as import29 from '../error-handling/error.service';
var renderType_ThemeStockAllocationComponent_Host:import0.RenderComponentType = (null as any);
class _View_ThemeStockAllocationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ThemeStockAllocationComponent_0_4:import3.ThemeStockAllocationComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent_Host0,renderType_ThemeStockAllocationComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-theme-stock-allocation',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ThemeStockAllocationComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ThemeStockAllocationComponent_0_4 = new import3.ThemeStockAllocationComponent(this.parentInjector.get(import8.ThemeService));
    this._appEl_0.initComponent(this._ThemeStockAllocationComponent_0_4,[],compView_0);
    compView_0.create(this._ThemeStockAllocationComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ThemeStockAllocationComponent) && (0 === requestNodeIndex))) { return this._ThemeStockAllocationComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ThemeStockAllocationComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemeStockAllocationComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ThemeStockAllocationComponent_Host === (null as any))) { (renderType_ThemeStockAllocationComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_ThemeStockAllocationComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ThemeStockAllocationComponentNgFactory:import10.ComponentFactory<import3.ThemeStockAllocationComponent> = new import10.ComponentFactory<import3.ThemeStockAllocationComponent>('app-theme-stock-allocation',viewFactory_ThemeStockAllocationComponent_Host0,import3.ThemeStockAllocationComponent);
const styles_ThemeStockAllocationComponent:any[] = ['hr[_ngcontent-%COMP%] {\n            margin-top: 0;\n        }\n        .userAllocatedStock[_ngcontent-%COMP%] {\n            border-style: solid;\n            border-width: 2px;\n            border-color: black;\n        }\n        button.no-decoration-element[_ngcontent-%COMP%], label.no-decoration-element[_ngcontent-%COMP%]:hover, label.no-decoration-element[_ngcontent-%COMP%]:focus {\n            background-color: white;\n            text-decoration: none;\n            outline:none;\n            border: none;\n            box-shadow: none;\n        }\n        label.inactive-element[_ngcontent-%COMP%]:hover, label.inactive-element[_ngcontent-%COMP%]:not(:hover), label.inactive-element[_ngcontent-%COMP%]:focus {\n            text-decoration: none;\n            outline:none;\n            box-shadow: none;\n            border-color: #ccc;\n            cursor: default;    \n        }\n        input[type="radio"][_ngcontent-%COMP%] {\n            visibility:hidden;\n        }\n        label.inactive-element[_ngcontent-%COMP%]:hover, label.inactive-element[_ngcontent-%COMP%]:not(:hover), label.inactive-element[_ngcontent-%COMP%]:focus {\n            text-decoration: none;\n            outline:none;\n            box-shadow: none;\n            border-color: #ccc;\n            cursor: default;    \n        }\n        .open[_ngcontent-%COMP%] > .dropdown-toggle[_ngcontent-%COMP%] {\n            background: white;\n            box-shadow: none;\n        }'];
var renderType_ThemeStockAllocationComponent:import0.RenderComponentType = (null as any);
class _View_ThemeStockAllocationComponent0 extends import1.AppView<import3.ThemeStockAllocationComponent> {
  _viewQuery_ModalComponent_0:import11.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgIf_9_6:import12.NgIf;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import12.NgIf;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import12.NgIf;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _ModalComponent_28_4:import13.ModalComponent;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent0,renderType_ThemeStockAllocationComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_ModalComponent_0 = new import11.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','row');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Stock Allocation',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = this.renderer.createElement(parentRenderNode,'hr',(null as any));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_9 = new import2.AppElement(9,(null as any),this,this._anchor_9);
    this._TemplateRef_9_5 = new import14.TemplateRef_(this._appEl_9,viewFactory_ThemeStockAllocationComponent1);
    this._NgIf_9_6 = new import12.NgIf(this._appEl_9.vcRef,this._TemplateRef_9_5);
    this._text_10 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_11 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_12 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','row');
    this._text_13 = this.renderer.createText(this._el_12,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','col-xs-10');
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'label',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'New Allocations',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_19 = this.renderer.createText(this._el_12,'\n',(null as any));
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_21 = this.renderer.createElement(parentRenderNode,'hr',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_23 = new import2.AppElement(23,(null as any),this,this._anchor_23);
    this._TemplateRef_23_5 = new import14.TemplateRef_(this._appEl_23,viewFactory_ThemeStockAllocationComponent8);
    this._NgIf_23_6 = new import12.NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_25 = new import2.AppElement(25,(null as any),this,this._anchor_25);
    this._TemplateRef_25_5 = new import14.TemplateRef_(this._appEl_25,viewFactory_ThemeStockAllocationComponent9);
    this._NgIf_25_6 = new import12.NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_28 = this.renderer.createElement(parentRenderNode,'app-modal',(null as any));
    this._appEl_28 = new import2.AppElement(28,(null as any),this,this._el_28);
    var compView_28:any = import15.viewFactory_ModalComponent0(this.viewUtils,this.injector(28),this._appEl_28);
    this._ModalComponent_28_4 = new import13.ModalComponent();
    this._appEl_28.initComponent(this._ModalComponent_28_4,[],compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','app-modal-header');
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'h5',(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'Delete your input',(null as any));
    this._text_34 = this.renderer.createText(this._el_30,'\n    ',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','app-modal-body');
    this._text_37 = this.renderer.createText(this._el_36,'\n        ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'p',(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Are you sure you want to delete your input to this stock allocation?',(null as any));
    this._text_40 = this.renderer.createText(this._el_36,'\n    ',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','app-modal-footer');
    this._text_43 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'button',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_44,'type','button');
    this._text_45 = this.renderer.createText(this._el_44,'Close',(null as any));
    this._text_46 = this.renderer.createText(this._el_42,'\n        ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_42,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_47,'type','button');
    this._text_48 = this.renderer.createText(this._el_47,'Delete',(null as any));
    this._text_49 = this.renderer.createText(this._el_42,'\n    ',(null as any));
    this._text_50 = this.renderer.createText((null as any),'\n',(null as any));
    compView_28.create(this._ModalComponent_28_4,[
      [].concat([this._el_30]),
      [].concat([this._el_36]),
      [].concat([this._el_42])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_44,'click',this.eventHandler(this._handle_click_44_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this._viewQuery_ModalComponent_0.reset([this._ModalComponent_28_4]);
    this.context.modal = this._viewQuery_ModalComponent_0.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import12.NgIf) && (9 === requestNodeIndex))) { return this._NgIf_9_6; }
    if (((token === import14.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import12.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6; }
    if (((token === import14.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import12.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6; }
    if (((token === import13.ModalComponent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._ModalComponent_28_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = (this.context.stockAllocationData.length > 0);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_9_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:boolean = !this.context.showAddOtherStocksButton;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_23_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.showAddOtherStocksButton;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_25_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._ModalComponent_28_4.hide()) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.deleteUserStockAllocation(this._ModalComponent_28_4)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ThemeStockAllocationComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ThemeStockAllocationComponent> {
  if ((renderType_ThemeStockAllocationComponent === (null as any))) { (renderType_ThemeStockAllocationComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/stock_allocation/theme-stock-allocation.component.html',0,import9.ViewEncapsulation.Emulated,styles_ThemeStockAllocationComponent,{})); }
  return new _View_ThemeStockAllocationComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import16.NgFor;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent1,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(this._el_0,(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import14.TemplateRef_(this._appEl_2,viewFactory_ThemeStockAllocationComponent2);
    this._NgFor_2_6 = new import16.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parentInjector.get(import17.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import16.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_0:any = this.parent.context.stockAllocationData;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgFor_2_6.ngForOf = currVal_0;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_0,currVal_0);
      this._expr_0 = currVal_0;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemeStockAllocationComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _el_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _anchor_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _TemplateRef_25_5:any;
  _NgIf_25_6:import12.NgIf;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import2.AppElement;
  _TemplateRef_27_5:any;
  _NgIf_27_6:import12.NgIf;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _anchor_36:any;
  /*private*/ _appEl_36:import2.AppElement;
  _TemplateRef_36_5:any;
  _NgIf_36_6:import12.NgIf;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _anchor_43:any;
  /*private*/ _appEl_43:import2.AppElement;
  _TemplateRef_43_5:any;
  _NgFor_43_6:import16.NgFor;
  _text_44:any;
  _text_45:any;
  _text_46:any;
  _el_47:any;
  _text_48:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent2,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','row');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-xs-5');
    this._text_5 = this.renderer.createText(this._el_4,'\n                ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'h5',(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n            ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','col-xs-7 text-right');
    this._text_11 = this.renderer.createText(this._el_10,'\n                ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','btn-group');
    this._text_13 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'aria-expanded','false');
    this.renderer.setElementAttribute(this._el_14,'aria-haspopup','true');
    this.renderer.setElementAttribute(this._el_14,'class','btn btn-default dropdown-toggle borderless no-decoration-element');
    this.renderer.setElementAttribute(this._el_14,'data-toggle','dropdown');
    this.renderer.setElementAttribute(this._el_14,'type','button');
    this._text_15 = this.renderer.createText(this._el_14,'\n                        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_16,'class','glyphicon glyphicon-pencil');
    this._text_17 = this.renderer.createText(this._el_14,'Rate Exposure\n                    ',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n                    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_12,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','dropdown-menu');
    this._text_20 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'li',(null as any));
    this._el_22 = this.renderer.createElement(this._el_21,'a',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'',(null as any));
    this._text_24 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._anchor_25 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_25 = new import2.AppElement(25,19,this,this._anchor_25);
    this._TemplateRef_25_5 = new import14.TemplateRef_(this._appEl_25,viewFactory_ThemeStockAllocationComponent3);
    this._NgIf_25_6 = new import12.NgIf(this._appEl_25.vcRef,this._TemplateRef_25_5);
    this._text_26 = this.renderer.createText(this._el_19,'\n                        ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._appEl_27 = new import2.AppElement(27,19,this,this._anchor_27);
    this._TemplateRef_27_5 = new import14.TemplateRef_(this._appEl_27,viewFactory_ThemeStockAllocationComponent4);
    this._NgIf_27_6 = new import12.NgIf(this._appEl_27.vcRef,this._TemplateRef_27_5);
    this._text_28 = this.renderer.createText(this._el_19,'\n                    ',(null as any));
    this._text_29 = this.renderer.createText(this._el_12,'\n                ',(null as any));
    this._text_30 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._text_33 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_34,'class','row');
    this._text_35 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._anchor_36 = this.renderer.createTemplateAnchor(this._el_34,(null as any));
    this._appEl_36 = new import2.AppElement(36,34,this,this._anchor_36);
    this._TemplateRef_36_5 = new import14.TemplateRef_(this._appEl_36,viewFactory_ThemeStockAllocationComponent5);
    this._NgIf_36_6 = new import12.NgIf(this._appEl_36.vcRef,this._TemplateRef_36_5);
    this._text_37 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._text_38 = this.renderer.createText(this._el_0,'\n\n        ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','row');
    this._text_40 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','btn-group btn-group-justified');
    this._text_42 = this.renderer.createText(this._el_41,'\n                ',(null as any));
    this._anchor_43 = this.renderer.createTemplateAnchor(this._el_41,(null as any));
    this._appEl_43 = new import2.AppElement(43,41,this,this._anchor_43);
    this._TemplateRef_43_5 = new import14.TemplateRef_(this._appEl_43,viewFactory_ThemeStockAllocationComponent7);
    this._NgFor_43_6 = new import16.NgFor(this._appEl_43.vcRef,this._TemplateRef_43_5,this.parent.parentInjector.get(import17.IterableDiffers),this.parent.parent.ref);
    this._text_44 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._text_45 = this.renderer.createText(this._el_39,'\n        ',(null as any));
    this._text_46 = this.renderer.createText(this._el_0,'\n        ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_0,'hr',(null as any));
    this._text_48 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_22,'click',this.eventHandler(this._handle_click_22_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._anchor_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._anchor_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._anchor_43,
      this._text_44,
      this._text_45,
      this._text_46,
      this._el_47,
      this._text_48
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (25 === requestNodeIndex))) { return this._TemplateRef_25_5; }
    if (((token === import12.NgIf) && (25 === requestNodeIndex))) { return this._NgIf_25_6; }
    if (((token === import14.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import12.NgIf) && (27 === requestNodeIndex))) { return this._NgIf_27_6; }
    if (((token === import14.TemplateRef) && (36 === requestNodeIndex))) { return this._TemplateRef_36_5; }
    if (((token === import12.NgIf) && (36 === requestNodeIndex))) { return this._NgIf_36_6; }
    if (((token === import14.TemplateRef) && (43 === requestNodeIndex))) { return this._TemplateRef_43_5; }
    if (((token === import16.NgFor) && (43 === requestNodeIndex))) { return this._NgFor_43_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_3:any = this.context.$implicit.userStockAllocation;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_25_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.$implicit.userStockAllocation;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgIf_27_6.ngIf = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.$implicit.isAllocationEditable;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgIf_36_6.ngIf = currVal_5;
      this._expr_5 = currVal_5;
    }
    changes = (null as any);
    const currVal_6:any = this.parent.parent.context.exposures;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgFor_43_6.ngForOf = currVal_6;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_6,currVal_6);
      this._expr_6 = currVal_6;
    }
    if ((changes !== (null as any))) { this._NgFor_43_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_43_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(2,'',((this.context.$implicit == (null as any))? (null as any): ((this.context.$implicit.themeStockComposition == (null as any))? (null as any): ((this.context.$implicit.themeStockComposition.stock == (null as any))? (null as any): this.context.$implicit.themeStockComposition.stock.companyName))),', ',((this.context.$implicit == (null as any))? (null as any): ((this.context.$implicit.themeStockComposition == (null as any))? (null as any): ((this.context.$implicit.themeStockComposition.stock == (null as any))? (null as any): this.context.$implicit.themeStockComposition.stock.country))),'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_7,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = import4.interpolate(1,'',(this.context.$implicit.userStockAllocation? 'Edit': 'Add'),'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_23,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.toggleStockAllocationEditable(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeStockAllocationComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent3 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent3,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','divider');
    this.renderer.setElementAttribute(this._el_0,'role','separator');
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return (null as any);
  }
}
function viewFactory_ThemeStockAllocationComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent4 extends import1.AppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent4,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._el_1 = this.renderer.createElement(this._el_0,'a',(null as any));
    this.renderer.setElementAttribute(this._el_1,'type','button');
    this._text_2 = this.renderer.createText(this._el_1,'Delete',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    (<_View_ThemeStockAllocationComponent0>this.parent.parent.parent)._ModalComponent_28_4.setData(this.parent.context.$implicit.userStockAllocation._id);
    const pd_0:any = ((<any>(<_View_ThemeStockAllocationComponent0>this.parent.parent.parent)._ModalComponent_28_4.show()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeStockAllocationComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import18.NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import19.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgFor_13_6:import16.NgFor;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent5,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','col-xs-6 col-xs-offset-6');
    this._text_1 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_2_3 = new import18.NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3;
    this._NgControlStatusGroup_2_5 = new import19.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n                    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','form-group row');
    this._text_5 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'label',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','col-xs-3 col-form-label');
    this.renderer.setElementAttribute(this._el_6,'for','exposure');
    this._text_7 = this.renderer.createText(this._el_6,'Select Exposure',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','col-xs-5');
    this._text_10 = this.renderer.createText(this._el_9,'\n                            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'select',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','form-control');
    this.renderer.setElementAttribute(this._el_11,'id','exposure');
    this.renderer.setElementAttribute(this._el_11,'name','exposure');
    this.renderer.setElementAttribute(this._el_11,'required','');
    this._text_12 = this.renderer.createText(this._el_11,'\n                                ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_13 = new import2.AppElement(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import14.TemplateRef_(this._appEl_13,viewFactory_ThemeStockAllocationComponent6);
    this._NgFor_13_6 = new import16.NgFor(this._appEl_13.vcRef,this._TemplateRef_13_5,this.parent.parent.parentInjector.get(import17.IterableDiffers),this.parent.parent.parent.ref);
    this._text_14 = this.renderer.createText(this._el_11,'\n                            ',(null as any));
    this._text_15 = this.renderer.createText(this._el_9,'\n                        ',(null as any));
    this._text_16 = this.renderer.createText(this._el_4,'\n                        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','col-xs-4');
    this._text_18 = this.renderer.createText(this._el_17,'\n                            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_19,'type','button');
    this._text_20 = this.renderer.createText(this._el_19,'Cancel',(null as any));
    this._text_21 = this.renderer.createText(this._el_17,'\n                            ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_17,'button',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_22,'type','submit');
    this._text_23 = this.renderer.createText(this._el_22,'Save',(null as any));
    this._text_24 = this.renderer.createText(this._el_17,'\n                        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_4,'\n                    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_2,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n            ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngSubmit',this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_2.bind(this)));
    const subscription_0:any = this._NgForm_2_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import16.NgFor) && (13 === requestNodeIndex))) { return this._NgFor_13_6; }
    if (((token === import18.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgForm_2_3; }
    if (((token === import20.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ControlContainer_2_4; }
    if (((token === import19.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgControlStatusGroup_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_9:any = this.parent.parent.parent.context.exposures;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgFor_13_6.ngForOf = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._NgFor_13_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_13_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:boolean = !this._NgForm_2_3.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_22,'disabled',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_ngSubmit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.createOrUpdateStockAllocation(this.parent.context.$implicit,this._el_11.selectedIndex.valueOf())) !== false);
    return (true && pd_0);
  }
  private _handle_submit_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.parent.context.toggleStockAllocationEditable(this.parent.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeStockAllocationComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent5(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent6 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import21.NgSelectOption;
  _NgSelectMultipleOption_0_4:import22.NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent6,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._NgSelectOption_0_3 = new import21.NgSelectOption(new import23.ElementRef(this._el_0),this.renderer,(null as any));
    this._NgSelectMultipleOption_0_4 = new import22.NgSelectMultipleOption(new import23.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3; }
    if (((token === import22.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.index;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgSelectOption_0_3.ngValue = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.index;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgSelectMultipleOption_0_4.ngValue = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
}
function viewFactory_ThemeStockAllocationComponent6(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent6(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent7 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent7,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn-group');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'label',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','btn btn-default inactive-element');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'p',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','text-center');
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n                ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.parent.parent.context.setExposureBackgroundColor(this.context.index);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementStyle(this._el_2,'backgroundColor',((this.viewUtils.sanitizer.sanitize(import24.SecurityContext.STYLE,currVal_0) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import24.SecurityContext.STYLE,currVal_0).toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = ((this.parent.context.$implicit.userStockAllocation && (this.parent.context.$implicit.userStockAllocation.exposure == this.context.index))? 'black': '');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_2,'borderColor',((this.viewUtils.sanitizer.sanitize(import24.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import24.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n                        ',this.parent.context.$implicit.exposures[this.context.index].percentage,'%\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_3,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.parent.parent.parent.context.exposures[this.context.index],'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_6,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ThemeStockAllocationComponent7(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent7(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent8 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent8,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn btn-primary');
    this._text_1 = this.renderer.createText(this._el_0,'Add Other Stocks',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.toggleShowAddOtherStocksButton()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeStockAllocationComponent8(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent8(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeStockAllocationComponent9 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import18.NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import19.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import2.AppElement;
  _AutocompleteDatasourceService_4_4:import25.AutocompleteDatasourceService;
  _AutoCompleteStockAllocationComponent_4_5:import26.AutoCompleteStockAllocationComponent;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeStockAllocationComponent9,renderType_ThemeStockAllocationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_2_3 = new import18.NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3;
    this._NgControlStatusGroup_2_5 = new import19.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'app-autocomplete-stock-allocation',(null as any));
    this._appEl_4 = new import2.AppElement(4,2,this,this._el_4);
    var compView_4:any = import27.viewFactory_AutoCompleteStockAllocationComponent0(this.viewUtils,this.injector(4),this._appEl_4);
    this._AutocompleteDatasourceService_4_4 = new import25.AutocompleteDatasourceService(this.parentInjector.get(import28.Http),this.parentInjector.get(import29.ErrorService));
    this._AutoCompleteStockAllocationComponent_4_5 = new import26.AutoCompleteStockAllocationComponent(this._AutocompleteDatasourceService_4_4);
    this._appEl_4.initComponent(this._AutoCompleteStockAllocationComponent_4_5,[],compView_4);
    compView_4.create(this._AutoCompleteStockAllocationComponent_4_5,[],(null as any));
    this._text_5 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_2,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','text-right');
    this._text_7 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_8,'type','button');
    this._text_9 = this.renderer.createText(this._el_8,'Cancel',(null as any));
    this._text_10 = this.renderer.createText(this._el_6,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_6,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_11,'formnovalidate','');
    this.renderer.setElementAttribute(this._el_11,'type','submit');
    this._text_12 = this.renderer.createText(this._el_11,'Save',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_14 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_2,'ngSubmit',this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_2.bind(this)));
    const subscription_0:any = this._NgForm_2_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_2_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.AutocompleteDatasourceService) && (4 === requestNodeIndex))) { return this._AutocompleteDatasourceService_4_4; }
    if (((token === import26.AutoCompleteStockAllocationComponent) && (4 === requestNodeIndex))) { return this._AutoCompleteStockAllocationComponent_4_5; }
    if (((token === import18.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgForm_2_3; }
    if (((token === import20.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ControlContainer_2_4; }
    if (((token === import19.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgControlStatusGroup_2_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_9:any = this.parent.context.allocatedStockIds;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._AutoCompleteStockAllocationComponent_4_5.preFilterStockIds = currVal_9;
      this._expr_9 = currVal_9;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:boolean = ((!this._NgForm_2_3.form.valid || !this._AutoCompleteStockAllocationComponent_4_5.selectedItems) || (this._AutoCompleteStockAllocationComponent_4_5.selectedItems.length == 0));
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_11,'disabled',currVal_11);
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_ngSubmit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.createStockCompositionAndAllocation(this._AutoCompleteStockAllocationComponent_4_5.selectedItems)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_2_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_2_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.toggleShowAddOtherStocksButton()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeStockAllocationComponent9(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeStockAllocationComponent9(viewUtils,parentInjector,declarationEl);
}