/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './theme-creation.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../services/theme.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/forms/src/directives/ng_form';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/validators';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '../autocomplete/autocomplete-datasource.service';
import * as import19 from '../autocomplete/autocomplete-tags.component';
import * as import20 from '@angular/common/src/directives/ng_for';
import * as import21 from '../autocomplete/autocomplete-stock-allocation.component';
import * as import22 from '@angular/router/src/directives/router_link';
import * as import23 from '@angular/router/src/directives/router_link_active';
import * as import24 from '@angular/core/src/linker/query_list';
import * as import25 from '../error_handling/error.component';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from '@angular/core/src/linker/template_ref';
import * as import28 from '../autocomplete/autocomplete-tags.component.ngfactory';
import * as import29 from '@angular/http/src/http';
import * as import30 from '../error_handling/error.service';
import * as import31 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import32 from '../autocomplete/autocomplete-stock-allocation.component.ngfactory';
import * as import33 from '@angular/router/src/router_state';
import * as import34 from '@angular/common/src/location/location_strategy';
import * as import35 from '../error_handling/error.component.ngfactory';
import * as import36 from '@angular/forms/src/validators';
import * as import37 from '@angular/forms/src/directives/control_value_accessor';
import * as import38 from '@angular/forms/src/directives/ng_control';
import * as import39 from '@angular/forms/src/directives/control_container';
import * as import40 from '@angular/core/src/security';
var renderType_ThemeCreationComponent_Host:import0.RenderComponentType = (null as any);
class _View_ThemeCreationComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ThemeCreationComponent_0_4:import3.ThemeCreationComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent_Host0,renderType_ThemeCreationComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-theme-create',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ThemeCreationComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ThemeCreationComponent_0_4 = new import3.ThemeCreationComponent(this.parentInjector.get(import8.ThemeService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._ThemeCreationComponent_0_4,[],compView_0);
    compView_0.create(this._ThemeCreationComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ThemeCreationComponent) && (0 === requestNodeIndex))) { return this._ThemeCreationComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_ThemeCreationComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ThemeCreationComponent_Host === (null as any))) { (renderType_ThemeCreationComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_ThemeCreationComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ThemeCreationComponentNgFactory:import11.ComponentFactory<import3.ThemeCreationComponent> = new import11.ComponentFactory<import3.ThemeCreationComponent>('app-theme-create',viewFactory_ThemeCreationComponent_Host0,import3.ThemeCreationComponent);
const styles_ThemeCreationComponent:any[] = ['.btn-default.active[_ngcontent-%COMP%], .btn-default[_ngcontent-%COMP%]:active {\n        background-color: #d9edf7\n    }'];
var renderType_ThemeCreationComponent:import0.RenderComponentType = (null as any);
class _View_ThemeCreationComponent0 extends import1.AppView<import3.ThemeCreationComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _NgForm_8_3:import12.NgForm;
  _ControlContainer_8_4:any;
  _NgControlStatusGroup_8_5:import13.NgControlStatusGroup;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _DefaultValueAccessor_17_3:import14.DefaultValueAccessor;
  _RequiredValidator_17_4:import15.RequiredValidator;
  _MinLengthValidator_17_5:import15.MinLengthValidator;
  _MaxLengthValidator_17_6:import15.MaxLengthValidator;
  _NG_VALIDATORS_17_7:any[];
  _NG_VALUE_ACCESSOR_17_8:any[];
  _NgModel_17_9:import16.NgModel;
  _NgControl_17_10:any;
  _NgControlStatus_17_11:import13.NgControlStatus;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import17.NgIf;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import2.AppElement;
  _AutocompleteDatasourceService_23_4:import18.AutocompleteDatasourceService;
  _AutoCompleteTagsComponent_23_5:import19.AutoCompleteTagsComponent;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _DefaultValueAccessor_32_3:import14.DefaultValueAccessor;
  _RequiredValidator_32_4:import15.RequiredValidator;
  _MinLengthValidator_32_5:import15.MinLengthValidator;
  _MaxLengthValidator_32_6:import15.MaxLengthValidator;
  _NG_VALIDATORS_32_7:any[];
  _NG_VALUE_ACCESSOR_32_8:any[];
  _NgModel_32_9:import16.NgModel;
  _NgControl_32_10:any;
  _NgControlStatus_32_11:import13.NgControlStatus;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _text_36:any;
  _anchor_37:any;
  /*private*/ _appEl_37:import2.AppElement;
  _TemplateRef_37_5:any;
  _NgIf_37_6:import17.NgIf;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _anchor_50:any;
  /*private*/ _appEl_50:import2.AppElement;
  _TemplateRef_50_5:any;
  _NgFor_50_6:import20.NgFor;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _anchor_64:any;
  /*private*/ _appEl_64:import2.AppElement;
  _TemplateRef_64_5:any;
  _NgFor_64_6:import20.NgFor;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _anchor_78:any;
  /*private*/ _appEl_78:import2.AppElement;
  _TemplateRef_78_5:any;
  _NgFor_78_6:import20.NgFor;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _el_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  /*private*/ _appEl_90:import2.AppElement;
  _AutocompleteDatasourceService_90_4:import18.AutocompleteDatasourceService;
  _AutoCompleteStockAllocationComponent_90_5:import21.AutoCompleteStockAllocationComponent;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _el_94:any;
  _RouterLinkWithHref_94_3:import22.RouterLinkWithHref;
  _RouterLinkActive_94_4:import23.RouterLinkActive;
  _query_RouterLink_94_0:import24.QueryList<any>;
  _query_RouterLinkWithHref_94_1:import24.QueryList<any>;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  /*private*/ _appEl_102:import2.AppElement;
  _ErrorComponent_102_4:import25.ErrorComponent;
  _text_103:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_41:any;
  /*private*/ _expr_42:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  _arr_0:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent0,renderType_ThemeCreationComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','well');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'fieldset',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','form-group');
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'legend',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Create new Theme',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'form',(null as any));
    this._NgForm_8_3 = new import12.NgForm((null as any),(null as any));
    this._ControlContainer_8_4 = this._NgForm_8_3;
    this._NgControlStatusGroup_8_5 = new import13.NgControlStatusGroup(this._ControlContainer_8_4);
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','form-group row');
    this._text_11 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_10,'label',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_12,'for','themeName');
    this._text_13 = this.renderer.createText(this._el_12,'Theme name',(null as any));
    this._text_14 = this.renderer.createText(this._el_10,'\n            ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_10,'div',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','col-xs-10');
    this._text_16 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'input',(null as any));
    this.renderer.setElementAttribute(this._el_17,'class','form-control');
    this.renderer.setElementAttribute(this._el_17,'id','themeName');
    this.renderer.setElementAttribute(this._el_17,'maxlength','32');
    this.renderer.setElementAttribute(this._el_17,'minlength','4');
    this.renderer.setElementAttribute(this._el_17,'name','themeName');
    this.renderer.setElementAttribute(this._el_17,'placeholder','Investment theme');
    this.renderer.setElementAttribute(this._el_17,'required','');
    this.renderer.setElementAttribute(this._el_17,'type','text');
    this._DefaultValueAccessor_17_3 = new import14.DefaultValueAccessor(this.renderer,new import26.ElementRef(this._el_17));
    this._RequiredValidator_17_4 = new import15.RequiredValidator();
    this._MinLengthValidator_17_5 = new import15.MinLengthValidator();
    this._MaxLengthValidator_17_6 = new import15.MaxLengthValidator();
    this._NG_VALIDATORS_17_7 = [
      this._RequiredValidator_17_4,
      this._MinLengthValidator_17_5,
      this._MaxLengthValidator_17_6
    ]
    ;
    this._NG_VALUE_ACCESSOR_17_8 = [this._DefaultValueAccessor_17_3];
    this._NgModel_17_9 = new import16.NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_17_7,(null as any),this._NG_VALUE_ACCESSOR_17_8);
    this._NgControl_17_10 = this._NgModel_17_9;
    this._NgControlStatus_17_11 = new import13.NgControlStatus(this._NgControl_17_10);
    this._text_18 = this.renderer.createText(this._el_15,'\n                ',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(this._el_15,(null as any));
    this._appEl_19 = new import2.AppElement(19,15,this,this._anchor_19);
    this._TemplateRef_19_5 = new import27.TemplateRef_(this._appEl_19,viewFactory_ThemeCreationComponent1);
    this._NgIf_19_6 = new import17.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(this._el_15,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_10,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_8,'app-autocomplete-tags',(null as any));
    this._appEl_23 = new import2.AppElement(23,8,this,this._el_23);
    var compView_23:any = import28.viewFactory_AutoCompleteTagsComponent0(this.viewUtils,this.injector(23),this._appEl_23);
    this._AutocompleteDatasourceService_23_4 = new import18.AutocompleteDatasourceService(this.parentInjector.get(import29.Http),this.parentInjector.get(import30.ErrorService));
    this._AutoCompleteTagsComponent_23_5 = new import19.AutoCompleteTagsComponent(this._AutocompleteDatasourceService_23_4);
    this._appEl_23.initComponent(this._AutoCompleteTagsComponent_23_5,[],compView_23);
    compView_23.create(this._AutoCompleteTagsComponent_23_5,[],(null as any));
    this._text_24 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','form-group row');
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_25,'label',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_27,'for','description');
    this._text_28 = this.renderer.createText(this._el_27,'Description',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_25,'div',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','col-xs-10');
    this._text_31 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_30,'textarea',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','form-control');
    this.renderer.setElementAttribute(this._el_32,'id','description');
    this.renderer.setElementAttribute(this._el_32,'minlength','4');
    this.renderer.setElementAttribute(this._el_32,'name','description');
    this.renderer.setElementAttribute(this._el_32,'placeholder','Please enter a description (min 4 characters, maximum 500 characters)');
    this.renderer.setElementAttribute(this._el_32,'required','');
    this.renderer.setElementAttribute(this._el_32,'rows','7');
    this._DefaultValueAccessor_32_3 = new import14.DefaultValueAccessor(this.renderer,new import26.ElementRef(this._el_32));
    this._RequiredValidator_32_4 = new import15.RequiredValidator();
    this._MinLengthValidator_32_5 = new import15.MinLengthValidator();
    this._MaxLengthValidator_32_6 = new import15.MaxLengthValidator();
    this._NG_VALIDATORS_32_7 = [
      this._RequiredValidator_32_4,
      this._MinLengthValidator_32_5,
      this._MaxLengthValidator_32_6
    ]
    ;
    this._NG_VALUE_ACCESSOR_32_8 = [this._DefaultValueAccessor_32_3];
    this._NgModel_32_9 = new import16.NgModel(this._ControlContainer_8_4,this._NG_VALIDATORS_32_7,(null as any),this._NG_VALUE_ACCESSOR_32_8);
    this._NgControl_32_10 = this._NgModel_32_9;
    this._NgControlStatus_32_11 = new import13.NgControlStatus(this._NgControl_32_10);
    this._text_33 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_30,'p',(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'',(null as any));
    this._text_36 = this.renderer.createText(this._el_30,'\n                ',(null as any));
    this._anchor_37 = this.renderer.createTemplateAnchor(this._el_30,(null as any));
    this._appEl_37 = new import2.AppElement(37,30,this,this._anchor_37);
    this._TemplateRef_37_5 = new import27.TemplateRef_(this._appEl_37,viewFactory_ThemeCreationComponent2);
    this._NgIf_37_6 = new import17.NgIf(this._appEl_37.vcRef,this._TemplateRef_37_5);
    this._text_38 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._text_39 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_40 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','form-group row');
    this._text_42 = this.renderer.createText(this._el_41,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_41,'label',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','col-xs-2 col-form-label');
    this._text_44 = this.renderer.createText(this._el_43,'Expected time horizon',(null as any));
    this._text_45 = this.renderer.createText(this._el_41,'\n\n            ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_41,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','col-xs-10');
    this._text_47 = this.renderer.createText(this._el_46,'\n                ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'div',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','btn-group btn-group-justified');
    this.renderer.setElementAttribute(this._el_48,'data-toggle','buttons');
    this._text_49 = this.renderer.createText(this._el_48,'\n                    ',(null as any));
    this._anchor_50 = this.renderer.createTemplateAnchor(this._el_48,(null as any));
    this._appEl_50 = new import2.AppElement(50,48,this,this._anchor_50);
    this._TemplateRef_50_5 = new import27.TemplateRef_(this._appEl_50,viewFactory_ThemeCreationComponent3);
    this._NgFor_50_6 = new import20.NgFor(this._appEl_50.vcRef,this._TemplateRef_50_5,this.parentInjector.get(import31.IterableDiffers),this.ref);
    this._text_51 = this.renderer.createText(this._el_48,'\n                ',(null as any));
    this._text_52 = this.renderer.createText(this._el_46,'\n            ',(null as any));
    this._text_53 = this.renderer.createText(this._el_41,'\n        ',(null as any));
    this._text_54 = this.renderer.createText(this._el_8,'\n\n\n        ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','form-group row');
    this._text_56 = this.renderer.createText(this._el_55,'\n            ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'label',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','col-xs-2 col-form-label');
    this._text_58 = this.renderer.createText(this._el_57,'Current theme maturity',(null as any));
    this._text_59 = this.renderer.createText(this._el_55,'\n\n            ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_55,'div',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','col-xs-10');
    this._text_61 = this.renderer.createText(this._el_60,'\n                ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'div',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','btn-group btn-group-justified');
    this.renderer.setElementAttribute(this._el_62,'data-toggle','buttons');
    this._text_63 = this.renderer.createText(this._el_62,'\n                    ',(null as any));
    this._anchor_64 = this.renderer.createTemplateAnchor(this._el_62,(null as any));
    this._appEl_64 = new import2.AppElement(64,62,this,this._anchor_64);
    this._TemplateRef_64_5 = new import27.TemplateRef_(this._appEl_64,viewFactory_ThemeCreationComponent4);
    this._NgFor_64_6 = new import20.NgFor(this._appEl_64.vcRef,this._TemplateRef_64_5,this.parentInjector.get(import31.IterableDiffers),this.ref);
    this._text_65 = this.renderer.createText(this._el_62,'\n                ',(null as any));
    this._text_66 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._text_67 = this.renderer.createText(this._el_55,'\n        ',(null as any));
    this._text_68 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._el_69 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','form-group row');
    this._text_70 = this.renderer.createText(this._el_69,'\n            ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_69,'label',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','col-xs-2 col-form-label');
    this._text_72 = this.renderer.createText(this._el_71,'Theme category',(null as any));
    this._text_73 = this.renderer.createText(this._el_69,'\n\n            ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_69,'div',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','col-xs-10');
    this._text_75 = this.renderer.createText(this._el_74,'\n                ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'div',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','btn-group btn-group-justified');
    this.renderer.setElementAttribute(this._el_76,'data-toggle','buttons');
    this._text_77 = this.renderer.createText(this._el_76,'\n                    ',(null as any));
    this._anchor_78 = this.renderer.createTemplateAnchor(this._el_76,(null as any));
    this._appEl_78 = new import2.AppElement(78,76,this,this._anchor_78);
    this._TemplateRef_78_5 = new import27.TemplateRef_(this._appEl_78,viewFactory_ThemeCreationComponent5);
    this._NgFor_78_6 = new import20.NgFor(this._appEl_78.vcRef,this._TemplateRef_78_5,this.parentInjector.get(import31.IterableDiffers),this.ref);
    this._text_79 = this.renderer.createText(this._el_76,'\n                ',(null as any));
    this._text_80 = this.renderer.createText(this._el_74,'\n            ',(null as any));
    this._text_81 = this.renderer.createText(this._el_69,'\n        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._text_83 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_8,'fieldset',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','form-group');
    this._text_85 = this.renderer.createText(this._el_84,'\n            ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_84,'legend',(null as any));
    this._text_87 = this.renderer.createText(this._el_86,'Stock Allocation',(null as any));
    this._text_88 = this.renderer.createText(this._el_84,'\n        ',(null as any));
    this._text_89 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_8,'app-autocomplete-stock-allocation',(null as any));
    this._appEl_90 = new import2.AppElement(90,8,this,this._el_90);
    var compView_90:any = import32.viewFactory_AutoCompleteStockAllocationComponent0(this.viewUtils,this.injector(90),this._appEl_90);
    this._AutocompleteDatasourceService_90_4 = new import18.AutocompleteDatasourceService(this.parentInjector.get(import29.Http),this.parentInjector.get(import30.ErrorService));
    this._AutoCompleteStockAllocationComponent_90_5 = new import21.AutoCompleteStockAllocationComponent(this._AutocompleteDatasourceService_90_4);
    this._appEl_90.initComponent(this._AutoCompleteStockAllocationComponent_90_5,[],compView_90);
    compView_90.create(this._AutoCompleteStockAllocationComponent_90_5,[],(null as any));
    this._text_91 = this.renderer.createText(this._el_8,'\n\n        ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_8,'div',(null as any));
    this.renderer.setElementAttribute(this._el_92,'class','text-right');
    this._text_93 = this.renderer.createText(this._el_92,'\n            ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_92,'a',(null as any));
    this.renderer.setElementAttribute(this._el_94,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_94,'role','button');
    this.renderer.setElementAttribute(this._el_94,'routerLinkActive','active');
    this._RouterLinkWithHref_94_3 = new import22.RouterLinkWithHref(this.parentInjector.get(import9.Router),this.parentInjector.get(import33.ActivatedRoute),this.parentInjector.get(import34.LocationStrategy));
    this._RouterLinkActive_94_4 = new import23.RouterLinkActive(this.parentInjector.get(import9.Router),new import26.ElementRef(this._el_94),this.renderer);
    this._query_RouterLink_94_0 = new import24.QueryList<any>();
    this._query_RouterLinkWithHref_94_1 = new import24.QueryList<any>();
    this._text_95 = this.renderer.createText(this._el_94,'Cancel',(null as any));
    this._text_96 = this.renderer.createText(this._el_92,'\n            ',(null as any));
    this._el_97 = this.renderer.createElement(this._el_92,'button',(null as any));
    this.renderer.setElementAttribute(this._el_97,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_97,'formnovalidate','');
    this.renderer.setElementAttribute(this._el_97,'type','submit');
    this._text_98 = this.renderer.createText(this._el_97,'Save',(null as any));
    this._text_99 = this.renderer.createText(this._el_92,'\n        ',(null as any));
    this._text_100 = this.renderer.createText(this._el_8,'\n\n    ',(null as any));
    this._text_101 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_0,'app-error',(null as any));
    this._appEl_102 = new import2.AppElement(102,0,this,this._el_102);
    var compView_102:any = import35.viewFactory_ErrorComponent0(this.viewUtils,this.injector(102),this._appEl_102);
    this._ErrorComponent_102_4 = new import25.ErrorComponent(this.parentInjector.get(import30.ErrorService));
    this._appEl_102.initComponent(this._ErrorComponent_102_4,[],compView_102);
    compView_102.create(this._ErrorComponent_102_4,[],(null as any));
    this._text_103 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'ngSubmit',this.eventHandler(this._handle_ngSubmit_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_8,'submit',this.eventHandler(this._handle_submit_8_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_8,'reset',this.eventHandler(this._handle_reset_8_2.bind(this)));
    const subscription_0:any = this._NgForm_8_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_8_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_17,'ngModelChange',this.eventHandler(this._handle_ngModelChange_17_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_17,'input',this.eventHandler(this._handle_input_17_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_17,'blur',this.eventHandler(this._handle_blur_17_2.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_17_9.update.subscribe(this.eventHandler(this._handle_ngModelChange_17_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_32,'ngModelChange',this.eventHandler(this._handle_ngModelChange_32_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_32,'input',this.eventHandler(this._handle_input_32_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_32,'blur',this.eventHandler(this._handle_blur_32_2.bind(this)));
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_32_9.update.subscribe(this.eventHandler(this._handle_ngModelChange_32_0.bind(this)));
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_41 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_94,'click',this.eventHandler(this._handle_click_94_0.bind(this)));
    this._arr_0 = import4.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._anchor_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._anchor_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._anchor_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._anchor_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._anchor_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (17 === requestNodeIndex))) { return this._DefaultValueAccessor_17_3; }
    if (((token === import15.RequiredValidator) && (17 === requestNodeIndex))) { return this._RequiredValidator_17_4; }
    if (((token === import15.MinLengthValidator) && (17 === requestNodeIndex))) { return this._MinLengthValidator_17_5; }
    if (((token === import15.MaxLengthValidator) && (17 === requestNodeIndex))) { return this._MaxLengthValidator_17_6; }
    if (((token === import36.NG_VALIDATORS) && (17 === requestNodeIndex))) { return this._NG_VALIDATORS_17_7; }
    if (((token === import37.NG_VALUE_ACCESSOR) && (17 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_17_8; }
    if (((token === import16.NgModel) && (17 === requestNodeIndex))) { return this._NgModel_17_9; }
    if (((token === import38.NgControl) && (17 === requestNodeIndex))) { return this._NgControl_17_10; }
    if (((token === import13.NgControlStatus) && (17 === requestNodeIndex))) { return this._NgControlStatus_17_11; }
    if (((token === import27.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import17.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    if (((token === import18.AutocompleteDatasourceService) && (23 === requestNodeIndex))) { return this._AutocompleteDatasourceService_23_4; }
    if (((token === import19.AutoCompleteTagsComponent) && (23 === requestNodeIndex))) { return this._AutoCompleteTagsComponent_23_5; }
    if (((token === import14.DefaultValueAccessor) && (32 === requestNodeIndex))) { return this._DefaultValueAccessor_32_3; }
    if (((token === import15.RequiredValidator) && (32 === requestNodeIndex))) { return this._RequiredValidator_32_4; }
    if (((token === import15.MinLengthValidator) && (32 === requestNodeIndex))) { return this._MinLengthValidator_32_5; }
    if (((token === import15.MaxLengthValidator) && (32 === requestNodeIndex))) { return this._MaxLengthValidator_32_6; }
    if (((token === import36.NG_VALIDATORS) && (32 === requestNodeIndex))) { return this._NG_VALIDATORS_32_7; }
    if (((token === import37.NG_VALUE_ACCESSOR) && (32 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_32_8; }
    if (((token === import16.NgModel) && (32 === requestNodeIndex))) { return this._NgModel_32_9; }
    if (((token === import38.NgControl) && (32 === requestNodeIndex))) { return this._NgControl_32_10; }
    if (((token === import13.NgControlStatus) && (32 === requestNodeIndex))) { return this._NgControlStatus_32_11; }
    if (((token === import27.TemplateRef) && (37 === requestNodeIndex))) { return this._TemplateRef_37_5; }
    if (((token === import17.NgIf) && (37 === requestNodeIndex))) { return this._NgIf_37_6; }
    if (((token === import27.TemplateRef) && (50 === requestNodeIndex))) { return this._TemplateRef_50_5; }
    if (((token === import20.NgFor) && (50 === requestNodeIndex))) { return this._NgFor_50_6; }
    if (((token === import27.TemplateRef) && (64 === requestNodeIndex))) { return this._TemplateRef_64_5; }
    if (((token === import20.NgFor) && (64 === requestNodeIndex))) { return this._NgFor_64_6; }
    if (((token === import27.TemplateRef) && (78 === requestNodeIndex))) { return this._TemplateRef_78_5; }
    if (((token === import20.NgFor) && (78 === requestNodeIndex))) { return this._NgFor_78_6; }
    if (((token === import18.AutocompleteDatasourceService) && (90 === requestNodeIndex))) { return this._AutocompleteDatasourceService_90_4; }
    if (((token === import21.AutoCompleteStockAllocationComponent) && (90 === requestNodeIndex))) { return this._AutoCompleteStockAllocationComponent_90_5; }
    if (((token === import22.RouterLinkWithHref) && ((94 <= requestNodeIndex) && (requestNodeIndex <= 95)))) { return this._RouterLinkWithHref_94_3; }
    if (((token === import23.RouterLinkActive) && ((94 <= requestNodeIndex) && (requestNodeIndex <= 95)))) { return this._RouterLinkActive_94_4; }
    if (((token === import12.NgForm) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._NgForm_8_3; }
    if (((token === import39.ControlContainer) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._ControlContainer_8_4; }
    if (((token === import13.NgControlStatusGroup) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._NgControlStatusGroup_8_5; }
    if (((token === import25.ErrorComponent) && (102 === requestNodeIndex))) { return this._ErrorComponent_102_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RequiredValidator_17_4.required = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_14:any = '4';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._MinLengthValidator_17_5.minlength = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_17_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_16:any = '32';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._MaxLengthValidator_17_6.maxlength = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['maxlength'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    if ((changes !== (null as any))) { this._MaxLengthValidator_17_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_18:any = 'themeName';
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._NgModel_17_9.name = currVal_18;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_18,currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this.context.theme.name;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._NgModel_17_9.model = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._NgModel_17_9.ngOnChanges(changes); }
    const currVal_26:any = (this._NgModel_17_9.dirty && !this._NgModel_17_9.valid);
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._NgIf_19_6.ngIf = currVal_26;
      this._expr_26 = currVal_26;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AutoCompleteTagsComponent_23_5.ngOnInit(); }
    const currVal_30:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._RequiredValidator_32_4.required = currVal_30;
      this._expr_30 = currVal_30;
    }
    changes = (null as any);
    const currVal_32:any = '4';
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._MinLengthValidator_32_5.minlength = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_32_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_34:any = this.context.maxDescriptionLength;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this._MaxLengthValidator_32_6.maxlength = currVal_34;
      if ((changes === (null as any))) { (changes = {}); }
      changes['maxlength'] = new import7.SimpleChange(this._expr_34,currVal_34);
      this._expr_34 = currVal_34;
    }
    if ((changes !== (null as any))) { this._MaxLengthValidator_32_6.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_36:any = 'description';
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this._NgModel_32_9.name = currVal_36;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_36,currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this.context.theme.description;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this._NgModel_32_9.model = currVal_37;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_37,currVal_37);
      this._expr_37 = currVal_37;
    }
    if ((changes !== (null as any))) { this._NgModel_32_9.ngOnChanges(changes); }
    const currVal_45:any = (this._NgModel_32_9.dirty && !this._NgModel_32_9.valid);
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this._NgIf_37_6.ngIf = currVal_45;
      this._expr_45 = currVal_45;
    }
    changes = (null as any);
    const currVal_46:any = this.context.timeHorizonValues;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this._NgFor_50_6.ngForOf = currVal_46;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_46,currVal_46);
      this._expr_46 = currVal_46;
    }
    if ((changes !== (null as any))) { this._NgFor_50_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_50_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_47:any = this.context.maturityValues;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this._NgFor_64_6.ngForOf = currVal_47;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_47,currVal_47);
      this._expr_47 = currVal_47;
    }
    if ((changes !== (null as any))) { this._NgFor_64_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_64_6.ngDoCheck(); }
    changes = (null as any);
    const currVal_48:any = this.context.categoryValues;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this._NgFor_78_6.ngForOf = currVal_48;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_48,currVal_48);
      this._expr_48 = currVal_48;
    }
    if ((changes !== (null as any))) { this._NgFor_78_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_78_6.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._AutoCompleteStockAllocationComponent_90_5.ngOnInit(); }
    changes = (null as any);
    const currVal_50:any = this._arr_0('/search');
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this._RouterLinkWithHref_94_3.routerLink = currVal_50;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_50,currVal_50);
      this._expr_50 = currVal_50;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_94_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_52:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this._RouterLinkActive_94_4.routerLinkActive = currVal_52;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_52,currVal_52);
      this._expr_52 = currVal_52;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_94_4.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ErrorComponent_102_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_94_0.dirty) {
        this._query_RouterLink_94_0.reset([]);
        this._RouterLinkActive_94_4.links = this._query_RouterLink_94_0;
        this._query_RouterLink_94_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_94_1.dirty) {
        this._query_RouterLinkWithHref_94_1.reset([this._RouterLinkWithHref_94_3]);
        this._RouterLinkActive_94_4.linksWithHrefs = this._query_RouterLinkWithHref_94_1;
        this._query_RouterLinkWithHref_94_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_94_4.ngAfterContentInit(); }
    }
    const currVal_3:any = this._NgControlStatusGroup_8_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_8,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_8_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_8,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_8_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_8,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_8_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_8,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_8_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_8,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_8_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_8,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = (this._RequiredValidator_17_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_17,'required',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = (this._MinLengthValidator_17_5.minlength? this._MinLengthValidator_17_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementAttribute(this._el_17,'minlength',((currVal_15 == (null as any))? (null as any): currVal_15.toString()));
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = (this._MaxLengthValidator_17_6.maxlength? this._MaxLengthValidator_17_6.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementAttribute(this._el_17,'maxlength',((currVal_17 == (null as any))? (null as any): currVal_17.toString()));
      this._expr_17 = currVal_17;
    }
    const currVal_20:any = this._NgControlStatus_17_11.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_17,'ng-untouched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_17_11.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_17,'ng-touched',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_17_11.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_17,'ng-pristine',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_17_11.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_17,'ng-dirty',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_17_11.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_17,'ng-valid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this._NgControlStatus_17_11.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_17,'ng-invalid',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_31:any = (this._RequiredValidator_32_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementAttribute(this._el_32,'required',((currVal_31 == (null as any))? (null as any): currVal_31.toString()));
      this._expr_31 = currVal_31;
    }
    const currVal_33:any = (this._MinLengthValidator_32_5.minlength? this._MinLengthValidator_32_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementAttribute(this._el_32,'minlength',((currVal_33 == (null as any))? (null as any): currVal_33.toString()));
      this._expr_33 = currVal_33;
    }
    const currVal_35:any = (this._MaxLengthValidator_32_6.maxlength? this._MaxLengthValidator_32_6.maxlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementAttribute(this._el_32,'maxlength',((currVal_35 == (null as any))? (null as any): currVal_35.toString()));
      this._expr_35 = currVal_35;
    }
    const currVal_38:any = this._NgControlStatus_32_11.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_32,'ng-untouched',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_32_11.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_32,'ng-touched',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_32_11.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_32,'ng-pristine',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_41:any = this._NgControlStatus_32_11.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_41,currVal_41)) {
      this.renderer.setElementClass(this._el_32,'ng-dirty',currVal_41);
      this._expr_41 = currVal_41;
    }
    const currVal_42:any = this._NgControlStatus_32_11.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setElementClass(this._el_32,'ng-valid',currVal_42);
      this._expr_42 = currVal_42;
    }
    const currVal_43:any = this._NgControlStatus_32_11.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_32,'ng-invalid',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = import4.interpolate(1,'',this.context.getDescriptionCharactersRemaining(),'');
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setText(this._text_35,currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_51:any = this._RouterLinkWithHref_94_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementProperty(this._el_94,'href',this.viewUtils.sanitizer.sanitize(import40.SecurityContext.URL,currVal_51));
      this._expr_51 = currVal_51;
    }
    const currVal_53:boolean = (!this._NgForm_8_3.form.valid || this.context.themeProperties.hasNoUserInputs());
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementProperty(this._el_97,'disabled',currVal_53);
      this._expr_53 = currVal_53;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_17_9.ngOnDestroy();
    this._NgModel_32_9.ngOnDestroy();
    this._RouterLinkWithHref_94_3.ngOnDestroy();
    this._RouterLinkActive_94_4.ngOnDestroy();
  }
  private _handle_ngSubmit_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_8_3,this._AutoCompleteTagsComponent_23_5,this._AutoCompleteStockAllocationComponent_90_5)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_8_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_8_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_8_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_8_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.theme.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_17_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_17_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_17_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_17_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_32_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.theme.description = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_32_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_32_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_32_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_32_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_94_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_94_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ThemeCreationComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ThemeCreationComponent> {
  if ((renderType_ThemeCreationComponent === (null as any))) { (renderType_ThemeCreationComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/theme_creation/theme-creation.component.html',0,import10.ViewEncapsulation.Emulated,styles_ThemeCreationComponent,{})); }
  return new _View_ThemeCreationComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeCreationComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent1,renderType_ThemeCreationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','data-validation-message');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    Theme name is required and between 4 to 34 characters\n                ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ThemeCreationComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeCreationComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeCreationComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent2,renderType_ThemeCreationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','data-validation-message');
    this._text_1 = this.renderer.createText(this._el_0,'\n                    Description is required and between 4 to 500 characters\n                ',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_ThemeCreationComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeCreationComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeCreationComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent3,renderType_ThemeCreationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'label',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn btn-default');
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','timeHorizon');
    this.renderer.setElementAttribute(this._el_2,'name','timeHorizon');
    this.renderer.setElementAttribute(this._el_2,'type','radio');
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.$implicit.value;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.description,'\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_3,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.themeProperties.setTimeHorizon(this.context.$implicit.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeCreationComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeCreationComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeCreationComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent4,renderType_ThemeCreationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'label',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn btn-default');
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','maturity');
    this.renderer.setElementAttribute(this._el_2,'name','maturity');
    this.renderer.setElementAttribute(this._el_2,'type','radio');
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.$implicit.value;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.description,'\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_3,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.themeProperties.setMaturity(this.context.$implicit.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeCreationComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeCreationComponent4(viewUtils,parentInjector,declarationEl);
}
class _View_ThemeCreationComponent5 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ThemeCreationComponent5,renderType_ThemeCreationComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'label',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','btn btn-default');
    this._text_1 = this.renderer.createText(this._el_0,'\n                        ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_2,'id','categories');
    this.renderer.setElementAttribute(this._el_2,'name','categories');
    this.renderer.setElementAttribute(this._el_2,'type','checkbox');
    this._text_3 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this.context.$implicit.value;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'value',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.description,'\n                    ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_3,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.themeProperties.toggleCheckedCategory(this.context.$implicit.value)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ThemeCreationComponent5(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ThemeCreationComponent5(viewUtils,parentInjector,declarationEl);
}