import {AutocompleteItem} from "./autocomplete-item";
export let items = [
    new AutocompleteItem('China'),
    new AutocompleteItem('India'),
    new AutocompleteItem('United States'),
    new AutocompleteItem('Indonesia'),
    new AutocompleteItem('Brazil'),
    new AutocompleteItem('Nigeria'),
    new AutocompleteItem('Bangladesh'),
    new AutocompleteItem('Russia'),
    new AutocompleteItem('Japan'),
    new AutocompleteItem('Mexico'),
    new AutocompleteItem('Philippines'),
    new AutocompleteItem('Ethiopia'),
    new AutocompleteItem('Vietnam'),
    new AutocompleteItem('Egypt'),
    new AutocompleteItem('Iran'),
    new AutocompleteItem('Egypt'),
    new AutocompleteItem('Germany'),
    new AutocompleteItem('Turkey'),
    new AutocompleteItem('Thailand'),
    new AutocompleteItem('France'),
    new AutocompleteItem('United Kingdom'),
    new AutocompleteItem('Italy')
];
