const THEME_PROPERTY_TIME_HORIZON = "timeHorizon";
const THEME_PROPERTY_MATURITY = "maturity";
const THEME_PROPERTY_CATEGORY = "categories";

const TIME_HORIZON_SHORT = 1;
const TIME_HORIZON_MEDIUM = 2;
const TIME_HORIZON_LONG = 3;

const MATURITY_UPCOMING = 1;
const MATURITY_NASCENT = 2;
const MATURITY_ACCELERATING = 3;
const MATURITY_MATURE = 4;
const MATURITY_DECLINING = 5;

const CATEGORY_ECONOMIC = 1;
const CATEGORY_TECHNOLOGIC = 2;
const CATEGORY_ENVIRONMENTAL = 3;
const CATEGORY_POLITICAL = 4;
const CATEGORY_REGULATORY = 5;
const CATEGORY_SOCIOLOGIC = 6;

const TOTAL_EXPOSURE_VALUES_NR = 5;
const EXPOSURE_VALUES = [0, 1, 2, 3, 4];

module.exports = {
    THEME_PROPERTY_TIME_HORIZON: THEME_PROPERTY_TIME_HORIZON,
    THEME_PROPERTY_MATURITY: THEME_PROPERTY_MATURITY,
    THEME_PROPERTY_CATEGORY: THEME_PROPERTY_CATEGORY,
    TIME_HORIZON_SHORT: TIME_HORIZON_SHORT,
    TIME_HORIZON_MEDIUM: TIME_HORIZON_MEDIUM,
    TIME_HORIZON_LONG: TIME_HORIZON_LONG,
    MATURITY_UPCOMING: MATURITY_UPCOMING,
    MATURITY_NASCENT: MATURITY_NASCENT,
    MATURITY_ACCELERATING: MATURITY_ACCELERATING,
    MATURITY_MATURE: MATURITY_MATURE,
    MATURITY_DECLINING: MATURITY_DECLINING,
    CATEGORY_ECONOMIC: CATEGORY_ECONOMIC,
    CATEGORY_TECHNOLOGIC: CATEGORY_TECHNOLOGIC,
    CATEGORY_ENVIRONMENTAL: CATEGORY_ENVIRONMENTAL,
    CATEGORY_POLITICAL: CATEGORY_POLITICAL,
    CATEGORY_REGULATORY: CATEGORY_REGULATORY,
    CATEGORY_SOCIOLOGIC: CATEGORY_SOCIOLOGIC,
    TOTAL_EXPOSURE_VALUES_NR: TOTAL_EXPOSURE_VALUES_NR,
    EXPOSURE_VALUES: EXPOSURE_VALUES
}