/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './about.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_AboutComponent_Host:import0.RenderComponentType = (null as any);
class _View_AboutComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AboutComponent_0_4:import3.AboutComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AboutComponent_Host0,renderType_AboutComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-about',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AboutComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AboutComponent_0_4 = new import3.AboutComponent();
    this._appEl_0.initComponent(this._AboutComponent_0_4,[],compView_0);
    compView_0.create(this._AboutComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AboutComponent) && (0 === requestNodeIndex))) { return this._AboutComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AboutComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AboutComponent_Host === (null as any))) { (renderType_AboutComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_AboutComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AboutComponentNgFactory:import9.ComponentFactory<import3.AboutComponent> = new import9.ComponentFactory<import3.AboutComponent>('app-about',viewFactory_AboutComponent_Host0,import3.AboutComponent);
const styles_AboutComponent:any[] = [];
var renderType_AboutComponent:import0.RenderComponentType = (null as any);
class _View_AboutComponent0 extends import1.AppView<import3.AboutComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AboutComponent0,renderType_AboutComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h1',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'Impressum',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'address',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'h5',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Marcel Maier',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_3,'h5',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Brünnsteinstrasse 10',(null as any));
    this._text_10 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_3,'h5',(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'81541 München',(null as any));
    this._text_13 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_3,'br',(null as any));
    this._text_15 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_3,'h5',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'marcel_maier at gmx . net',(null as any));
    this._text_18 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_3,'h5',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'00 49 186 231 86 481',(null as any));
    this._text_21 = this.renderer.createText(this._el_3,'\n',(null as any));
    this.init([],[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_AboutComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AboutComponent> {
  if ((renderType_AboutComponent === (null as any))) { (renderType_AboutComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/static_pages/about.component.html',0,import8.ViewEncapsulation.None,styles_AboutComponent,{})); }
  return new _View_AboutComponent0(viewUtils,parentInjector,declarationEl);
}