/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from './signup.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from './auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/forms/src/directives/ng_form';
import * as import13 from '@angular/forms/src/directives/ng_control_status';
import * as import14 from '@angular/forms/src/directives/default_value_accessor';
import * as import15 from '@angular/forms/src/directives/validators';
import * as import16 from '@angular/forms/src/directives/ng_model';
import * as import17 from '@angular/forms/src/directives/select_control_value_accessor';
import * as import18 from '@angular/common/src/directives/ng_for';
import * as import19 from '../error_handling/error.component';
import * as import20 from '@angular/core/src/linker/element_ref';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from '../error_handling/error.component.ngfactory';
import * as import24 from '../error_handling/error.service';
import * as import25 from '@angular/forms/src/validators';
import * as import26 from '@angular/forms/src/directives/control_value_accessor';
import * as import27 from '@angular/forms/src/directives/ng_control';
import * as import28 from '@angular/forms/src/directives/control_container';
import * as import29 from '@angular/forms/src/directives/select_multiple_control_value_accessor';
var renderType_SignupComponent_Host:import0.RenderComponentType = (null as any);
class _View_SignupComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _SignupComponent_0_4:import3.SignupComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent_Host0,renderType_SignupComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-signup',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupComponent_0_4 = new import3.SignupComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._SignupComponent_0_4,[],compView_0);
    compView_0.create(this._SignupComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.SignupComponent) && (0 === requestNodeIndex))) { return this._SignupComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_SignupComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_SignupComponent_Host === (null as any))) { (renderType_SignupComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_SignupComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupComponentNgFactory:import11.ComponentFactory<import3.SignupComponent> = new import11.ComponentFactory<import3.SignupComponent>('app-signup',viewFactory_SignupComponent_Host0,import3.SignupComponent);
const styles_SignupComponent:any[] = [];
var renderType_SignupComponent:import0.RenderComponentType = (null as any);
class _View_SignupComponent0 extends import1.AppView<import3.SignupComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _NgForm_7_3:import12.NgForm;
  _ControlContainer_7_4:any;
  _NgControlStatusGroup_7_5:import13.NgControlStatusGroup;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _DefaultValueAccessor_16_3:import14.DefaultValueAccessor;
  _RequiredValidator_16_4:import15.RequiredValidator;
  _MinLengthValidator_16_5:import15.MinLengthValidator;
  _NG_VALIDATORS_16_6:any[];
  _NG_VALUE_ACCESSOR_16_7:any[];
  _NgModel_16_8:import16.NgModel;
  _NgControl_16_9:any;
  _NgControlStatus_16_10:import13.NgControlStatus;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _DefaultValueAccessor_30_3:import14.DefaultValueAccessor;
  _RequiredValidator_30_4:import15.RequiredValidator;
  _PatternValidator_30_5:import15.PatternValidator;
  _NG_VALIDATORS_30_6:any[];
  _NG_VALUE_ACCESSOR_30_7:any[];
  _NgModel_30_8:import16.NgModel;
  _NgControl_30_9:any;
  _NgControlStatus_30_10:import13.NgControlStatus;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _DefaultValueAccessor_44_3:import14.DefaultValueAccessor;
  _RequiredValidator_44_4:import15.RequiredValidator;
  _MinLengthValidator_44_5:import15.MinLengthValidator;
  _NG_VALIDATORS_44_6:any[];
  _NG_VALUE_ACCESSOR_44_7:any[];
  _NgModel_44_8:import16.NgModel;
  _NgControl_44_9:any;
  _NgControlStatus_44_10:import13.NgControlStatus;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _SelectControlValueAccessor_58_3:import17.SelectControlValueAccessor;
  _RequiredValidator_58_4:import15.RequiredValidator;
  _NG_VALIDATORS_58_5:any[];
  _NG_VALUE_ACCESSOR_58_6:any[];
  _NgModel_58_7:import16.NgModel;
  _NgControl_58_8:any;
  _NgControlStatus_58_9:import13.NgControlStatus;
  _text_59:any;
  _anchor_60:any;
  /*private*/ _appEl_60:import2.AppElement;
  _TemplateRef_60_5:any;
  _NgFor_60_6:import18.NgFor;
  _text_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _el_75:any;
  _DefaultValueAccessor_75_3:import14.DefaultValueAccessor;
  _RequiredValidator_75_4:import15.RequiredValidator;
  _NG_VALIDATORS_75_5:any[];
  _NG_VALUE_ACCESSOR_75_6:any[];
  _NgModel_75_7:import16.NgModel;
  _NgControl_75_8:any;
  _NgControlStatus_75_9:import13.NgControlStatus;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  /*private*/ _appEl_88:import2.AppElement;
  _ErrorComponent_88_4:import19.ErrorComponent;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_49:any;
  /*private*/ _expr_50:any;
  /*private*/ _expr_51:any;
  /*private*/ _expr_52:any;
  /*private*/ _expr_53:any;
  /*private*/ _expr_54:any;
  /*private*/ _expr_55:any;
  /*private*/ _expr_56:any;
  /*private*/ _expr_60:any;
  /*private*/ _expr_61:any;
  /*private*/ _expr_62:any;
  /*private*/ _expr_63:any;
  /*private*/ _expr_64:any;
  /*private*/ _expr_65:any;
  /*private*/ _expr_66:any;
  /*private*/ _expr_67:any;
  /*private*/ _expr_68:any;
  /*private*/ _expr_69:any;
  /*private*/ _expr_70:any;
  /*private*/ _expr_71:any;
  /*private*/ _expr_75:any;
  /*private*/ _expr_76:any;
  /*private*/ _expr_77:any;
  /*private*/ _expr_78:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  /*private*/ _expr_82:any;
  /*private*/ _expr_83:any;
  /*private*/ _expr_84:any;
  /*private*/ _expr_85:any;
  /*private*/ _expr_86:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent0,renderType_SignupComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','container');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','well col-xs-offset-3 col-xs-6');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'h1',(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'Sign up',(null as any));
    this._text_6 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_2,'form',(null as any));
    this._NgForm_7_3 = new import12.NgForm((null as any),(null as any));
    this._ControlContainer_7_4 = this._NgForm_7_3;
    this._NgControlStatusGroup_7_5 = new import13.NgControlStatusGroup(this._ControlContainer_7_4);
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','form-group row');
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_9,'label',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_11,'for','name');
    this._text_12 = this.renderer.createText(this._el_11,'Name',(null as any));
    this._text_13 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_9,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','col-xs-10');
    this._text_15 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'input',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','form-control');
    this.renderer.setElementAttribute(this._el_16,'id','name');
    this.renderer.setElementAttribute(this._el_16,'minlength','4');
    this.renderer.setElementAttribute(this._el_16,'name','name');
    this.renderer.setElementAttribute(this._el_16,'required','');
    this.renderer.setElementAttribute(this._el_16,'type','text');
    this._DefaultValueAccessor_16_3 = new import14.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_16));
    this._RequiredValidator_16_4 = new import15.RequiredValidator();
    this._MinLengthValidator_16_5 = new import15.MinLengthValidator();
    this._NG_VALIDATORS_16_6 = [
      this._RequiredValidator_16_4,
      this._MinLengthValidator_16_5
    ]
    ;
    this._NG_VALUE_ACCESSOR_16_7 = [this._DefaultValueAccessor_16_3];
    this._NgModel_16_8 = new import16.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_16_6,(null as any),this._NG_VALUE_ACCESSOR_16_7);
    this._NgControl_16_9 = this._NgModel_16_8;
    this._NgControlStatus_16_10 = new import13.NgControlStatus(this._NgControl_16_9);
    this._text_17 = this.renderer.createText(this._el_14,'\n                ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_14,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','data-validation-message');
    this._text_19 = this.renderer.createText(this._el_18,'Name is required and with 4 characters minimum',(null as any));
    this._text_20 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_22 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','form-group row');
    this._text_24 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_23,'label',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_25,'for','email');
    this._text_26 = this.renderer.createText(this._el_25,'Email',(null as any));
    this._text_27 = this.renderer.createText(this._el_23,'\n            ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_23,'div',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','col-xs-10');
    this._text_29 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'input',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','form-control');
    this.renderer.setElementAttribute(this._el_30,'id','email');
    this.renderer.setElementAttribute(this._el_30,'name','email');
    this.renderer.setElementAttribute(this._el_30,'pattern','[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,3}$');
    this.renderer.setElementAttribute(this._el_30,'required','');
    this.renderer.setElementAttribute(this._el_30,'type','email');
    this._DefaultValueAccessor_30_3 = new import14.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_30));
    this._RequiredValidator_30_4 = new import15.RequiredValidator();
    this._PatternValidator_30_5 = new import15.PatternValidator();
    this._NG_VALIDATORS_30_6 = [
      this._RequiredValidator_30_4,
      this._PatternValidator_30_5
    ]
    ;
    this._NG_VALUE_ACCESSOR_30_7 = [this._DefaultValueAccessor_30_3];
    this._NgModel_30_8 = new import16.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_30_6,(null as any),this._NG_VALUE_ACCESSOR_30_7);
    this._NgControl_30_9 = this._NgModel_30_8;
    this._NgControlStatus_30_10 = new import13.NgControlStatus(this._NgControl_30_9);
    this._text_31 = this.renderer.createText(this._el_28,'\n                ',(null as any));
    this._el_32 = this.renderer.createElement(this._el_28,'div',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','data-validation-message');
    this._text_33 = this.renderer.createText(this._el_32,'Email is required and with valid syntax',(null as any));
    this._text_34 = this.renderer.createText(this._el_28,'\n            ',(null as any));
    this._text_35 = this.renderer.createText(this._el_23,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','form-group row');
    this._text_38 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'label',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_39,'for','password');
    this._text_40 = this.renderer.createText(this._el_39,'Password',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_37,'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','col-xs-10');
    this._text_43 = this.renderer.createText(this._el_42,'\n                ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'input',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','form-control');
    this.renderer.setElementAttribute(this._el_44,'id','password');
    this.renderer.setElementAttribute(this._el_44,'minlength','8');
    this.renderer.setElementAttribute(this._el_44,'name','password');
    this.renderer.setElementAttribute(this._el_44,'required','');
    this.renderer.setElementAttribute(this._el_44,'type','password');
    this._DefaultValueAccessor_44_3 = new import14.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_44));
    this._RequiredValidator_44_4 = new import15.RequiredValidator();
    this._MinLengthValidator_44_5 = new import15.MinLengthValidator();
    this._NG_VALIDATORS_44_6 = [
      this._RequiredValidator_44_4,
      this._MinLengthValidator_44_5
    ]
    ;
    this._NG_VALUE_ACCESSOR_44_7 = [this._DefaultValueAccessor_44_3];
    this._NgModel_44_8 = new import16.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_44_6,(null as any),this._NG_VALUE_ACCESSOR_44_7);
    this._NgControl_44_9 = this._NgModel_44_8;
    this._NgControlStatus_44_10 = new import13.NgControlStatus(this._NgControl_44_9);
    this._text_45 = this.renderer.createText(this._el_42,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_42,'div',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','data-validation-message');
    this._text_47 = this.renderer.createText(this._el_46,'Password is required and with 8 characters minimum',(null as any));
    this._text_48 = this.renderer.createText(this._el_42,'\n            ',(null as any));
    this._text_49 = this.renderer.createText(this._el_37,'\n        ',(null as any));
    this._text_50 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_51,'class','form-group row');
    this._text_52 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'label',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_53,'for','personalRole');
    this._text_54 = this.renderer.createText(this._el_53,'Personal Role',(null as any));
    this._text_55 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_51,'div',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','col-xs-10');
    this._text_57 = this.renderer.createText(this._el_56,'\n                ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'select',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','form-control');
    this.renderer.setElementAttribute(this._el_58,'id','personalRole');
    this.renderer.setElementAttribute(this._el_58,'name','personalRole');
    this.renderer.setElementAttribute(this._el_58,'required','');
    this._SelectControlValueAccessor_58_3 = new import17.SelectControlValueAccessor(this.renderer,new import20.ElementRef(this._el_58));
    this._RequiredValidator_58_4 = new import15.RequiredValidator();
    this._NG_VALIDATORS_58_5 = [this._RequiredValidator_58_4];
    this._NG_VALUE_ACCESSOR_58_6 = [this._SelectControlValueAccessor_58_3];
    this._NgModel_58_7 = new import16.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_58_5,(null as any),this._NG_VALUE_ACCESSOR_58_6);
    this._NgControl_58_8 = this._NgModel_58_7;
    this._NgControlStatus_58_9 = new import13.NgControlStatus(this._NgControl_58_8);
    this._text_59 = this.renderer.createText(this._el_58,'\n                    ',(null as any));
    this._anchor_60 = this.renderer.createTemplateAnchor(this._el_58,(null as any));
    this._appEl_60 = new import2.AppElement(60,58,this,this._anchor_60);
    this._TemplateRef_60_5 = new import21.TemplateRef_(this._appEl_60,viewFactory_SignupComponent1);
    this._NgFor_60_6 = new import18.NgFor(this._appEl_60.vcRef,this._TemplateRef_60_5,this.parentInjector.get(import22.IterableDiffers),this.ref);
    this._text_61 = this.renderer.createText(this._el_58,'\n                ',(null as any));
    this._text_62 = this.renderer.createText(this._el_56,'\n                ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_56,'div',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','data-validation-message');
    this._text_64 = this.renderer.createText(this._el_63,'Personal Role is required',(null as any));
    this._text_65 = this.renderer.createText(this._el_56,'\n            ',(null as any));
    this._text_66 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._text_67 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','form-group row');
    this._text_69 = this.renderer.createText(this._el_68,'\n            ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_68,'label',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','col-xs-2 col-form-label');
    this.renderer.setElementAttribute(this._el_70,'for','accessCode');
    this._text_71 = this.renderer.createText(this._el_70,'Access Code',(null as any));
    this._text_72 = this.renderer.createText(this._el_68,'\n            ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_68,'div',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','col-xs-10');
    this._text_74 = this.renderer.createText(this._el_73,'\n                ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'input',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','form-control');
    this.renderer.setElementAttribute(this._el_75,'id','accessCode');
    this.renderer.setElementAttribute(this._el_75,'name','accessCode');
    this.renderer.setElementAttribute(this._el_75,'required','');
    this.renderer.setElementAttribute(this._el_75,'type','text');
    this._DefaultValueAccessor_75_3 = new import14.DefaultValueAccessor(this.renderer,new import20.ElementRef(this._el_75));
    this._RequiredValidator_75_4 = new import15.RequiredValidator();
    this._NG_VALIDATORS_75_5 = [this._RequiredValidator_75_4];
    this._NG_VALUE_ACCESSOR_75_6 = [this._DefaultValueAccessor_75_3];
    this._NgModel_75_7 = new import16.NgModel(this._ControlContainer_7_4,this._NG_VALIDATORS_75_5,(null as any),this._NG_VALUE_ACCESSOR_75_6);
    this._NgControl_75_8 = this._NgModel_75_7;
    this._NgControlStatus_75_9 = new import13.NgControlStatus(this._NgControl_75_8);
    this._text_76 = this.renderer.createText(this._el_73,'\n                ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_73,'div',(null as any));
    this.renderer.setElementAttribute(this._el_77,'class','data-validation-message');
    this._text_78 = this.renderer.createText(this._el_77,'Access Code is required',(null as any));
    this._text_79 = this.renderer.createText(this._el_73,'\n            ',(null as any));
    this._text_80 = this.renderer.createText(this._el_68,'\n        ',(null as any));
    this._text_81 = this.renderer.createText(this._el_7,'\n\n        ',(null as any));
    this._el_82 = this.renderer.createElement(this._el_7,'div',(null as any));
    this.renderer.setElementAttribute(this._el_82,'class','text-right');
    this._text_83 = this.renderer.createText(this._el_82,'\n            ',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'button',(null as any));
    this.renderer.setElementAttribute(this._el_84,'class','btn btn-primary');
    this.renderer.setElementAttribute(this._el_84,'type','submit');
    this._text_85 = this.renderer.createText(this._el_84,'Sign up',(null as any));
    this._text_86 = this.renderer.createText(this._el_82,'\n        ',(null as any));
    this._text_87 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_7,'app-error',(null as any));
    this._appEl_88 = new import2.AppElement(88,7,this,this._el_88);
    var compView_88:any = import23.viewFactory_ErrorComponent0(this.viewUtils,this.injector(88),this._appEl_88);
    this._ErrorComponent_88_4 = new import19.ErrorComponent(this.parentInjector.get(import24.ErrorService));
    this._appEl_88.initComponent(this._ErrorComponent_88_4,[],compView_88);
    compView_88.create(this._ErrorComponent_88_4,[],(null as any));
    this._text_89 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._text_90 = this.renderer.createText(this._el_2,'\n\n    ',(null as any));
    this._text_91 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_7,'ngSubmit',this.eventHandler(this._handle_ngSubmit_7_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'submit',this.eventHandler(this._handle_submit_7_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_7,'reset',this.eventHandler(this._handle_reset_7_2.bind(this)));
    const subscription_0:any = this._NgForm_7_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_7_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_16,'ngModelChange',this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_16,'input',this.eventHandler(this._handle_input_16_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_16,'blur',this.eventHandler(this._handle_blur_16_2.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_16_8.update.subscribe(this.eventHandler(this._handle_ngModelChange_16_0.bind(this)));
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_30,'ngModelChange',this.eventHandler(this._handle_ngModelChange_30_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_30,'input',this.eventHandler(this._handle_input_30_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_30,'blur',this.eventHandler(this._handle_blur_30_2.bind(this)));
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    const subscription_2:any = this._NgModel_30_8.update.subscribe(this.eventHandler(this._handle_ngModelChange_30_0.bind(this)));
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_9:Function = this.renderer.listen(this._el_44,'ngModelChange',this.eventHandler(this._handle_ngModelChange_44_0.bind(this)));
    var disposable_10:Function = this.renderer.listen(this._el_44,'input',this.eventHandler(this._handle_input_44_1.bind(this)));
    var disposable_11:Function = this.renderer.listen(this._el_44,'blur',this.eventHandler(this._handle_blur_44_2.bind(this)));
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_49 = import7.UNINITIALIZED;
    const subscription_3:any = this._NgModel_44_8.update.subscribe(this.eventHandler(this._handle_ngModelChange_44_0.bind(this)));
    this._expr_50 = import7.UNINITIALIZED;
    this._expr_51 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    this._expr_53 = import7.UNINITIALIZED;
    this._expr_54 = import7.UNINITIALIZED;
    this._expr_55 = import7.UNINITIALIZED;
    this._expr_56 = import7.UNINITIALIZED;
    var disposable_12:Function = this.renderer.listen(this._el_58,'ngModelChange',this.eventHandler(this._handle_ngModelChange_58_0.bind(this)));
    var disposable_13:Function = this.renderer.listen(this._el_58,'change',this.eventHandler(this._handle_change_58_1.bind(this)));
    var disposable_14:Function = this.renderer.listen(this._el_58,'blur',this.eventHandler(this._handle_blur_58_2.bind(this)));
    this._expr_60 = import7.UNINITIALIZED;
    this._expr_61 = import7.UNINITIALIZED;
    this._expr_62 = import7.UNINITIALIZED;
    this._expr_63 = import7.UNINITIALIZED;
    const subscription_4:any = this._NgModel_58_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_58_0.bind(this)));
    this._expr_64 = import7.UNINITIALIZED;
    this._expr_65 = import7.UNINITIALIZED;
    this._expr_66 = import7.UNINITIALIZED;
    this._expr_67 = import7.UNINITIALIZED;
    this._expr_68 = import7.UNINITIALIZED;
    this._expr_69 = import7.UNINITIALIZED;
    this._expr_70 = import7.UNINITIALIZED;
    this._expr_71 = import7.UNINITIALIZED;
    var disposable_15:Function = this.renderer.listen(this._el_75,'ngModelChange',this.eventHandler(this._handle_ngModelChange_75_0.bind(this)));
    var disposable_16:Function = this.renderer.listen(this._el_75,'input',this.eventHandler(this._handle_input_75_1.bind(this)));
    var disposable_17:Function = this.renderer.listen(this._el_75,'blur',this.eventHandler(this._handle_blur_75_2.bind(this)));
    this._expr_75 = import7.UNINITIALIZED;
    this._expr_76 = import7.UNINITIALIZED;
    this._expr_77 = import7.UNINITIALIZED;
    this._expr_78 = import7.UNINITIALIZED;
    const subscription_5:any = this._NgModel_75_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_75_0.bind(this)));
    this._expr_79 = import7.UNINITIALIZED;
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_81 = import7.UNINITIALIZED;
    this._expr_82 = import7.UNINITIALIZED;
    this._expr_83 = import7.UNINITIALIZED;
    this._expr_84 = import7.UNINITIALIZED;
    this._expr_85 = import7.UNINITIALIZED;
    this._expr_86 = import7.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._anchor_60,
      this._text_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9,
      disposable_10,
      disposable_11,
      disposable_12,
      disposable_13,
      disposable_14,
      disposable_15,
      disposable_16,
      disposable_17
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4,
      subscription_5
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.DefaultValueAccessor) && (16 === requestNodeIndex))) { return this._DefaultValueAccessor_16_3; }
    if (((token === import15.RequiredValidator) && (16 === requestNodeIndex))) { return this._RequiredValidator_16_4; }
    if (((token === import15.MinLengthValidator) && (16 === requestNodeIndex))) { return this._MinLengthValidator_16_5; }
    if (((token === import25.NG_VALIDATORS) && (16 === requestNodeIndex))) { return this._NG_VALIDATORS_16_6; }
    if (((token === import26.NG_VALUE_ACCESSOR) && (16 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_16_7; }
    if (((token === import16.NgModel) && (16 === requestNodeIndex))) { return this._NgModel_16_8; }
    if (((token === import27.NgControl) && (16 === requestNodeIndex))) { return this._NgControl_16_9; }
    if (((token === import13.NgControlStatus) && (16 === requestNodeIndex))) { return this._NgControlStatus_16_10; }
    if (((token === import14.DefaultValueAccessor) && (30 === requestNodeIndex))) { return this._DefaultValueAccessor_30_3; }
    if (((token === import15.RequiredValidator) && (30 === requestNodeIndex))) { return this._RequiredValidator_30_4; }
    if (((token === import15.PatternValidator) && (30 === requestNodeIndex))) { return this._PatternValidator_30_5; }
    if (((token === import25.NG_VALIDATORS) && (30 === requestNodeIndex))) { return this._NG_VALIDATORS_30_6; }
    if (((token === import26.NG_VALUE_ACCESSOR) && (30 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_30_7; }
    if (((token === import16.NgModel) && (30 === requestNodeIndex))) { return this._NgModel_30_8; }
    if (((token === import27.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_9; }
    if (((token === import13.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_10; }
    if (((token === import14.DefaultValueAccessor) && (44 === requestNodeIndex))) { return this._DefaultValueAccessor_44_3; }
    if (((token === import15.RequiredValidator) && (44 === requestNodeIndex))) { return this._RequiredValidator_44_4; }
    if (((token === import15.MinLengthValidator) && (44 === requestNodeIndex))) { return this._MinLengthValidator_44_5; }
    if (((token === import25.NG_VALIDATORS) && (44 === requestNodeIndex))) { return this._NG_VALIDATORS_44_6; }
    if (((token === import26.NG_VALUE_ACCESSOR) && (44 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_44_7; }
    if (((token === import16.NgModel) && (44 === requestNodeIndex))) { return this._NgModel_44_8; }
    if (((token === import27.NgControl) && (44 === requestNodeIndex))) { return this._NgControl_44_9; }
    if (((token === import13.NgControlStatus) && (44 === requestNodeIndex))) { return this._NgControlStatus_44_10; }
    if (((token === import21.TemplateRef) && (60 === requestNodeIndex))) { return this._TemplateRef_60_5; }
    if (((token === import18.NgFor) && (60 === requestNodeIndex))) { return this._NgFor_60_6; }
    if (((token === import17.SelectControlValueAccessor) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._SelectControlValueAccessor_58_3; }
    if (((token === import15.RequiredValidator) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._RequiredValidator_58_4; }
    if (((token === import25.NG_VALIDATORS) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NG_VALIDATORS_58_5; }
    if (((token === import26.NG_VALUE_ACCESSOR) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NG_VALUE_ACCESSOR_58_6; }
    if (((token === import16.NgModel) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NgModel_58_7; }
    if (((token === import27.NgControl) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NgControl_58_8; }
    if (((token === import13.NgControlStatus) && ((58 <= requestNodeIndex) && (requestNodeIndex <= 61)))) { return this._NgControlStatus_58_9; }
    if (((token === import14.DefaultValueAccessor) && (75 === requestNodeIndex))) { return this._DefaultValueAccessor_75_3; }
    if (((token === import15.RequiredValidator) && (75 === requestNodeIndex))) { return this._RequiredValidator_75_4; }
    if (((token === import25.NG_VALIDATORS) && (75 === requestNodeIndex))) { return this._NG_VALIDATORS_75_5; }
    if (((token === import26.NG_VALUE_ACCESSOR) && (75 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_75_6; }
    if (((token === import16.NgModel) && (75 === requestNodeIndex))) { return this._NgModel_75_7; }
    if (((token === import27.NgControl) && (75 === requestNodeIndex))) { return this._NgControl_75_8; }
    if (((token === import13.NgControlStatus) && (75 === requestNodeIndex))) { return this._NgControlStatus_75_9; }
    if (((token === import19.ErrorComponent) && (88 === requestNodeIndex))) { return this._ErrorComponent_88_4; }
    if (((token === import12.NgForm) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._NgForm_7_3; }
    if (((token === import28.ControlContainer) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._ControlContainer_7_4; }
    if (((token === import13.NgControlStatusGroup) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._NgControlStatusGroup_7_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_12:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._RequiredValidator_16_4.required = currVal_12;
      this._expr_12 = currVal_12;
    }
    changes = (null as any);
    const currVal_14:any = '4';
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._MinLengthValidator_16_5.minlength = currVal_14;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_14,currVal_14);
      this._expr_14 = currVal_14;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_16_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_16:any = 'name';
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgModel_16_8.name = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this.context.user.name;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._NgModel_16_8.model = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._NgModel_16_8.ngOnChanges(changes); }
    const currVal_28:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._RequiredValidator_30_4.required = currVal_28;
      this._expr_28 = currVal_28;
    }
    changes = (null as any);
    const currVal_30:any = '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,3}$';
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this._PatternValidator_30_5.pattern = currVal_30;
      if ((changes === (null as any))) { (changes = {}); }
      changes['pattern'] = new import7.SimpleChange(this._expr_30,currVal_30);
      this._expr_30 = currVal_30;
    }
    if ((changes !== (null as any))) { this._PatternValidator_30_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_32:any = 'email';
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this._NgModel_30_8.name = currVal_32;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_32,currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this.context.user.email;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this._NgModel_30_8.model = currVal_33;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_33,currVal_33);
      this._expr_33 = currVal_33;
    }
    if ((changes !== (null as any))) { this._NgModel_30_8.ngOnChanges(changes); }
    const currVal_44:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this._RequiredValidator_44_4.required = currVal_44;
      this._expr_44 = currVal_44;
    }
    changes = (null as any);
    const currVal_46:any = '8';
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this._MinLengthValidator_44_5.minlength = currVal_46;
      if ((changes === (null as any))) { (changes = {}); }
      changes['minlength'] = new import7.SimpleChange(this._expr_46,currVal_46);
      this._expr_46 = currVal_46;
    }
    if ((changes !== (null as any))) { this._MinLengthValidator_44_5.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_48:any = 'password';
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this._NgModel_44_8.name = currVal_48;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_48,currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_49:any = this.context.user.password;
    if (import4.checkBinding(throwOnChange,this._expr_49,currVal_49)) {
      this._NgModel_44_8.model = currVal_49;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_49,currVal_49);
      this._expr_49 = currVal_49;
    }
    if ((changes !== (null as any))) { this._NgModel_44_8.ngOnChanges(changes); }
    const currVal_60:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this._RequiredValidator_58_4.required = currVal_60;
      this._expr_60 = currVal_60;
    }
    changes = (null as any);
    const currVal_62:any = 'personalRole';
    if (import4.checkBinding(throwOnChange,this._expr_62,currVal_62)) {
      this._NgModel_58_7.name = currVal_62;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_62,currVal_62);
      this._expr_62 = currVal_62;
    }
    const currVal_63:any = this.context.user.personalRole;
    if (import4.checkBinding(throwOnChange,this._expr_63,currVal_63)) {
      this._NgModel_58_7.model = currVal_63;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_63,currVal_63);
      this._expr_63 = currVal_63;
    }
    if ((changes !== (null as any))) { this._NgModel_58_7.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_70:any = this.context.personalRoles;
    if (import4.checkBinding(throwOnChange,this._expr_70,currVal_70)) {
      this._NgFor_60_6.ngForOf = currVal_70;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_70,currVal_70);
      this._expr_70 = currVal_70;
    }
    if ((changes !== (null as any))) { this._NgFor_60_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_60_6.ngDoCheck(); }
    const currVal_75:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_75,currVal_75)) {
      this._RequiredValidator_75_4.required = currVal_75;
      this._expr_75 = currVal_75;
    }
    changes = (null as any);
    const currVal_77:any = 'accessCode';
    if (import4.checkBinding(throwOnChange,this._expr_77,currVal_77)) {
      this._NgModel_75_7.name = currVal_77;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_77,currVal_77);
      this._expr_77 = currVal_77;
    }
    const currVal_78:any = this.context.registrationAccessCode;
    if (import4.checkBinding(throwOnChange,this._expr_78,currVal_78)) {
      this._NgModel_75_7.model = currVal_78;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_78,currVal_78);
      this._expr_78 = currVal_78;
    }
    if ((changes !== (null as any))) { this._NgModel_75_7.ngOnChanges(changes); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ErrorComponent_88_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_7_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_7,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_7_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_7,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_7_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_7,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_7_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_7,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_7_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_7_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_7,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_13:any = (this._RequiredValidator_16_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementAttribute(this._el_16,'required',((currVal_13 == (null as any))? (null as any): currVal_13.toString()));
      this._expr_13 = currVal_13;
    }
    const currVal_15:any = (this._MinLengthValidator_16_5.minlength? this._MinLengthValidator_16_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementAttribute(this._el_16,'minlength',((currVal_15 == (null as any))? (null as any): currVal_15.toString()));
      this._expr_15 = currVal_15;
    }
    const currVal_18:any = this._NgControlStatus_16_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_16,'ng-untouched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_16_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_16,'ng-touched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_16_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_16,'ng-pristine',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_16_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_16,'ng-dirty',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_16_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_16,'ng-valid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_16_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_16,'ng-invalid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = (this._NgModel_16_8.valid || this._NgModel_16_8.pristine);
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementProperty(this._el_18,'hidden',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_29:any = (this._RequiredValidator_30_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementAttribute(this._el_30,'required',((currVal_29 == (null as any))? (null as any): currVal_29.toString()));
      this._expr_29 = currVal_29;
    }
    const currVal_31:any = (this._PatternValidator_30_5.pattern? this._PatternValidator_30_5.pattern: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementAttribute(this._el_30,'pattern',((currVal_31 == (null as any))? (null as any): currVal_31.toString()));
      this._expr_31 = currVal_31;
    }
    const currVal_34:any = this._NgControlStatus_30_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_30_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_30_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_30_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_30_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_30_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = (this._NgModel_30_8.valid || this._NgModel_30_8.pristine);
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementProperty(this._el_32,'hidden',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_45:any = (this._RequiredValidator_44_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementAttribute(this._el_44,'required',((currVal_45 == (null as any))? (null as any): currVal_45.toString()));
      this._expr_45 = currVal_45;
    }
    const currVal_47:any = (this._MinLengthValidator_44_5.minlength? this._MinLengthValidator_44_5.minlength: (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementAttribute(this._el_44,'minlength',((currVal_47 == (null as any))? (null as any): currVal_47.toString()));
      this._expr_47 = currVal_47;
    }
    const currVal_50:any = this._NgControlStatus_44_10.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_50,currVal_50)) {
      this.renderer.setElementClass(this._el_44,'ng-untouched',currVal_50);
      this._expr_50 = currVal_50;
    }
    const currVal_51:any = this._NgControlStatus_44_10.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_51,currVal_51)) {
      this.renderer.setElementClass(this._el_44,'ng-touched',currVal_51);
      this._expr_51 = currVal_51;
    }
    const currVal_52:any = this._NgControlStatus_44_10.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementClass(this._el_44,'ng-pristine',currVal_52);
      this._expr_52 = currVal_52;
    }
    const currVal_53:any = this._NgControlStatus_44_10.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_53,currVal_53)) {
      this.renderer.setElementClass(this._el_44,'ng-dirty',currVal_53);
      this._expr_53 = currVal_53;
    }
    const currVal_54:any = this._NgControlStatus_44_10.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_54,currVal_54)) {
      this.renderer.setElementClass(this._el_44,'ng-valid',currVal_54);
      this._expr_54 = currVal_54;
    }
    const currVal_55:any = this._NgControlStatus_44_10.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_55,currVal_55)) {
      this.renderer.setElementClass(this._el_44,'ng-invalid',currVal_55);
      this._expr_55 = currVal_55;
    }
    const currVal_56:any = (this._NgModel_44_8.valid || this._NgModel_44_8.pristine);
    if (import4.checkBinding(throwOnChange,this._expr_56,currVal_56)) {
      this.renderer.setElementProperty(this._el_46,'hidden',currVal_56);
      this._expr_56 = currVal_56;
    }
    const currVal_61:any = (this._RequiredValidator_58_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_61,currVal_61)) {
      this.renderer.setElementAttribute(this._el_58,'required',((currVal_61 == (null as any))? (null as any): currVal_61.toString()));
      this._expr_61 = currVal_61;
    }
    const currVal_64:any = this._NgControlStatus_58_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_64,currVal_64)) {
      this.renderer.setElementClass(this._el_58,'ng-untouched',currVal_64);
      this._expr_64 = currVal_64;
    }
    const currVal_65:any = this._NgControlStatus_58_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_65,currVal_65)) {
      this.renderer.setElementClass(this._el_58,'ng-touched',currVal_65);
      this._expr_65 = currVal_65;
    }
    const currVal_66:any = this._NgControlStatus_58_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_66,currVal_66)) {
      this.renderer.setElementClass(this._el_58,'ng-pristine',currVal_66);
      this._expr_66 = currVal_66;
    }
    const currVal_67:any = this._NgControlStatus_58_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_67,currVal_67)) {
      this.renderer.setElementClass(this._el_58,'ng-dirty',currVal_67);
      this._expr_67 = currVal_67;
    }
    const currVal_68:any = this._NgControlStatus_58_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_68,currVal_68)) {
      this.renderer.setElementClass(this._el_58,'ng-valid',currVal_68);
      this._expr_68 = currVal_68;
    }
    const currVal_69:any = this._NgControlStatus_58_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_69,currVal_69)) {
      this.renderer.setElementClass(this._el_58,'ng-invalid',currVal_69);
      this._expr_69 = currVal_69;
    }
    const currVal_71:any = (this._NgModel_58_7.valid || this._NgModel_58_7.pristine);
    if (import4.checkBinding(throwOnChange,this._expr_71,currVal_71)) {
      this.renderer.setElementProperty(this._el_63,'hidden',currVal_71);
      this._expr_71 = currVal_71;
    }
    const currVal_76:any = (this._RequiredValidator_75_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_76,currVal_76)) {
      this.renderer.setElementAttribute(this._el_75,'required',((currVal_76 == (null as any))? (null as any): currVal_76.toString()));
      this._expr_76 = currVal_76;
    }
    const currVal_79:any = this._NgControlStatus_75_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setElementClass(this._el_75,'ng-untouched',currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = this._NgControlStatus_75_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setElementClass(this._el_75,'ng-touched',currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = this._NgControlStatus_75_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setElementClass(this._el_75,'ng-pristine',currVal_81);
      this._expr_81 = currVal_81;
    }
    const currVal_82:any = this._NgControlStatus_75_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_82,currVal_82)) {
      this.renderer.setElementClass(this._el_75,'ng-dirty',currVal_82);
      this._expr_82 = currVal_82;
    }
    const currVal_83:any = this._NgControlStatus_75_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_83,currVal_83)) {
      this.renderer.setElementClass(this._el_75,'ng-valid',currVal_83);
      this._expr_83 = currVal_83;
    }
    const currVal_84:any = this._NgControlStatus_75_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_84,currVal_84)) {
      this.renderer.setElementClass(this._el_75,'ng-invalid',currVal_84);
      this._expr_84 = currVal_84;
    }
    const currVal_85:any = (this._NgModel_75_7.valid || this._NgModel_75_7.pristine);
    if (import4.checkBinding(throwOnChange,this._expr_85,currVal_85)) {
      this.renderer.setElementProperty(this._el_77,'hidden',currVal_85);
      this._expr_85 = currVal_85;
    }
    const currVal_86:boolean = !this._NgForm_7_3.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_86,currVal_86)) {
      this.renderer.setElementProperty(this._el_84,'disabled',currVal_86);
      this._expr_86 = currVal_86;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_16_8.ngOnDestroy();
    this._NgModel_30_8.ngOnDestroy();
    this._NgModel_44_8.ngOnDestroy();
    this._NgModel_58_7.ngOnDestroy();
    this._NgModel_75_7.ngOnDestroy();
  }
  private _handle_ngSubmit_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onSubmit(this._NgForm_7_3)) !== false);
    return (true && pd_0);
  }
  private _handle_submit_7_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_reset_7_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_7_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_16_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_16_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_16_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_16_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_30_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_30_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_30_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_30_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_44_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_44_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_44_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_44_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_58_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.user.personalRole = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_change_58_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_58_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_58_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._SelectControlValueAccessor_58_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_75_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.registrationAccessCode = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_75_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_75_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_75_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_75_3.onTouched()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.SignupComponent> {
  if ((renderType_SignupComponent === (null as any))) { (renderType_SignupComponent = viewUtils.createRenderComponentType('/Users/evisa/Thematicum/client/app/auth/signup.component.html',0,import10.ViewEncapsulation.None,styles_SignupComponent,{})); }
  return new _View_SignupComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SignupComponent1 extends import1.AppView<any> {
  _el_0:any;
  _NgSelectOption_0_3:import17.NgSelectOption;
  _NgSelectMultipleOption_0_4:import29.NgSelectMultipleOption;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_SignupComponent1,renderType_SignupComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'option',(null as any));
    this._NgSelectOption_0_3 = new import17.NgSelectOption(new import20.ElementRef(this._el_0),this.renderer,(<_View_SignupComponent0>this.parent)._SelectControlValueAccessor_58_3);
    this._NgSelectMultipleOption_0_4 = new import29.NgSelectMultipleOption(new import20.ElementRef(this._el_0),this.renderer,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.NgSelectOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectOption_0_3; }
    if (((token === import29.NgSelectMultipleOption) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._NgSelectMultipleOption_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgSelectOption_0_3.ngValue = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgSelectMultipleOption_0_4.ngValue = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgSelectOption_0_3.ngOnDestroy();
    this._NgSelectMultipleOption_0_4.ngOnDestroy();
  }
}
function viewFactory_SignupComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_SignupComponent1(viewUtils,parentInjector,declarationEl);
}